description_dict = {
    'nv1_cre_01' : 'Demonstra consciência do som virando os olhos e a cabeça.',
    'nv1_cre_02' : 'Demonstra consciência do som tornando-se mais ativo, virando os olhos e a cabeça para a pessoa.',
    'nv1_cre_03' : 'Demonstra consciência da voz ao virar os olhos e cabeça para a pessoa.',
    'nv1_cre_04' : 'Segue quando adulto aponta para imagem, com o olhar e/ou gesto (p.e. tocar ou apontar a imagem).',
    'nv1_cre_05' : 'Responde ao ponto proximal olhando e colocando o objeto na localização indicada pelo adulto.',
    'nv1_cre_06' : 'Vira os olhos e a cabeça na direção do objeto. Interlocutor apresenta',
    'nv1_cre_07' : 'Vira os olhos e a cabeça em direção ao parceiro.',
    'nv1_cre_08' : 'Vira a cabeça para o objeto ou localização. Objeto próximo a ela; ela vai até ele.',
    'nv1_cre_09' : 'Aproxima-se e pega o objeto.',
    'nv1_cre_10' : 'Assiste e responde a uma ou mais tomadas de vez. Os jogos sociais incluem o "Cadê?", "Formiguinha" e Cócegas.',
    'nv1_cre_11' : 'O mesmo que no item anterior. Presta atenção e responde durante canções a um ou mais versos.',
    'nv1_cre_12' : 'Interrompe uma atividade contínua quando dito "Não", "Para", ou demonstra consciência, fazendo uma pausa temporária, virando os olhos e a cabeça para o adulto, ou mostrando angústia (p.e. chorando).',
    'nv1_cre_13' : 'Responde ao gesto e à fala do adulto, colocando ou tentando colocar o objeto na mão do adulto.',
    'nv1_cre_14' : 'Realiza a ação com pistas verbais/gestuais. Tem de executar pelo menos cinco ações na primeira oportunidade. Os exemplos incluem o adulto repetir a instrução, usar verbos para destacar a ação (p.e., bater na cadeira para sentar; segurar o balde para guardar), ou ajudar a criança parcialmente durante a ação.',
    'nv1_cre_15' : 'Executa a ação sem os gestos ou orientação física do adulto. O adulto pode repetir as instruções uma segunda vez, sem a pista gestual.',
    #
    'nv1_cex_01' : 'Tenta alcançar o objeto desejado que está nas mãos do adulto para indicar o pedido. O gesto não precisa ser acompanhado pelo contato visual ou vocalizações/palavras. Não inclui o aproximar para agarrar.',
    'nv1_cex_02' : 'Vocaliza em conjunto com o contato visual e/ou gesto (p.e. tentar alcançar) para pedir um item ou objeto desejado.',
    'nv1_cex_03' : 'Indica que precisa de ajuda oferecendo ou colocando o objeto na mão do adulto, verbalizando ou olhando para o adulto. O gesto não precisa ser acompanhado pelo contato visual ou emissões orais.',
    'nv1_cex_04' : 'Balbucia e/ou vocaliza com contato visual em pelo menos dois turnos.',
    'nv1_cex_05' : 'O gesto não precisa ser acompanhado pelo contato visual ou emissões. Considere outros gestos convencionais (balançar a cabeça, sinal de "acabou") ou emissões ("não").',
    'nv1_cex_06' : 'Toca ou aponta para o objeto a 15-30 cm com o dedo indicador (a mão não está aberta) para indicar o pedido. O objeto pode estar na mão do adulto ou ao alcance da criança.',
    'nv1_cex_07' : 'Vira a cabeça e os olhos para o adulto e faz contato visual por 1-2 segundos, com ou sem gesto (p.e. alcançar, agarrar) para solicitar o objeto. O contato visual e os gestos não precisam ser acompanhados por emissões.',
    'nv1_cex_08' : 'O adulto segura dois objetos, um em cada mão. A criança toca ou aponta para o objeto desejado com o dedo indicador (a mão não está aberta). O gesto não precisa ser acompanhado pelo contato visual ou emissões.',
    'nv1_cex_09' : 'Vira a cabeça e os olhos para o adulto e faz contato visual enquanto vocaliza para pedir o objeto desejado. A vocalização pode ser uma aproximação. P.e.: "ooh" para bola e "iih" para ir.',
    'nv1_cex_10' : 'Usa o dedo indicador (a mão não está aberta) para apontar para o objeto desejado, 90 cm ou mais de distância da criança).',
    'nv1_cex_11' : 'O adulto segura dois objetos, um em cada mão, mas fora do alcance da criança e dizendo o nome de cada objeto. A criança aponta para o objeto desejado que está longe do seu alcance com o dedo indicador (a mão não está aberta). O gesto não precisa ser acompanhado pelo contato visual ou emissões.',
    'nv1_cex_12' : 'Os exemplos incluem "ba-ba", "ma-ma". A vocalização não precisa ser acompanhada de contato visual ou gesto.',
    'nv1_cex_13' : 'As vocalizações ocorrem com ou sem modelo verbal do adulto. As vocalizações durante o jogo contam.',
    'nv1_cex_14' : 'Os exemplos incluem "ba-bu", "ma-vu" e sequências de jargão.',
    #
    'nv1_cso_01' : 'A criança não mostra evitamento, desistência ou afeto negativo.',
    'nv1_cso_02' : 'As ajudas motoras incluem: alcançar, imitar o movimento do adulto, entregar um item ou objeto ao adulto. Não precisa ser acompanhada de contato visual.',
    'nv1_cso_03' : 'Atenta ao olhar e mantém o contato visual com a outra pessoa por 2 segundos.',
    'nv1_cso_04' : 'Mostra interesse na rotina social sensorial abordando, observando ou participando ativamente e solicitando a continuação da rotina através do contato visual, gestos (p.e. alcançando, imitando o movimento do adulto) ou vocalizando.',
    'nv1_cso_05' : 'A resposta não precisa ser acompanhada de contato visual.',
    'nv1_cso_06' : 'Mostra interesse na atividade observando e imitando o adulto fazendo ações e dá continuidade ao esquema de jogo imitado.',
    'nv1_cso_07' : 'Participa duas vezes ou mais em qualquer comportamento ativo (alcançar, imitar, vocalizar) durante um jogo. O contato visual e o sorriso isolado não são suficientes. Exemplos de atividades: "Cadê o...", "Era uma vez uma formiguinha...", músicas, livros, bolinha de sabão.',
    'nv1_cso_08' : 'Demonstra consciência da saudação, virando a cabeça e olhando para o adulto por 2-3 segundos. A resposta não precisa ser acompanhada de gestos ou vocalizações.',
    'nv1_cso_09' : 'Demonstra consciência da saudação, virando a cabeça e o corpo e vocalizando "Olá/Tchau" com contato visual por 2-3 segundos.',
    'nv1_cso_10' : 'Partilha sorrisos com contato visual por 2-3 segundos durante a atividade de jogo com o adulto.',
    #
    'nv1_imi_01' : 'Imita oito ou mais ações com objetos até 5 segundos após o modelo do adulto. P.e.: bater dois objetos um contra o outro, colocar um objeto dentro de um recipiente ou rolar um objeto).',
    'nv1_imi_02' : 'Imita 10 ações motoras diferentes até 5 segundos após modelo do adulto. Imita duas ações diferentes por música em quatro a cinco rotinas diferentes.',
    'nv1_imi_03' : 'Imita seis ações diferentes. P.e.: colocar as mãos na cabeça, nas orelhas ou palmadinhas nas bochechas.',
    'nv1_imi_04' : 'Imita movimentos oro-faciais até 5 segundos após o modelo do adulto. P.e.: mostrar a língua, vibrar a língua, lábios, encher as bochechas de ar.',
    #
    'nv1_cog_01' : 'Pode ser em resposta à pista verbal ("Coloca aqui") ou física ("Mão sobre mão) do adulto nas primeiras tentativas, mas a criança precisa completar a correspondência/classificação de forma autônoma pelo menos para cinco objetos diferentes. P.e, agrupar trens e carros; lápis e papel; palitos e círculos em recipientes separados.',
    'nv1_cog_02' : 'Igual acima para pelo menos cinco imagens diferentes.',
    'nv1_cog_03' : 'Igual acima para pelo menos cinco pares de objeto/imagem diferentes.',
    'nv1_cog_04' : 'Igual acima para cinco ou mais cores.',
    #
    'nv1_jog_01' : 'A ação deve ser iniciada pela criança e não em resposta ao modelo do adulto. O comportamento adapta-se às características do objeto. P.e.: agitar o chocalho, bater com martelo, rolar ou bater a bola, ou empilhar blocos.',
    'nv1_jog_02' : 'O jogo é adequado ao desenvolvimento (p.e., não é restrito ou repetitivo), relaciona-se com o objeto/atividade e envolve ações de um passo com objetos. P.e.: inserir blocos num jogo de encaixe, colocar bolas num labirinto, colocar pinos em orifícios, desmanchar sequências de contas encaixadas.',
    'nv1_jog_03' : 'O jogo envolve a conclusão autônoma do objeto/atividade. Passa com cinco ou mais brinquedos. P.e.: inserir anéis num pino; pôr e tirar copos encaixados; empilhar blocos ou colocar pinos em orifícios.',
    'nv1_jog_04' : 'O jogo relaciona-se com o objeto/atividade e envolve ações de um passo com objetos. Passa com 8-10 brinquedos. P.e.: atirar bolas, rolar carrinhos ou bater num tambor.',
    'nv1_jog_05' : 'O jogo envolve a conclusão autônoma do objeto/atividade. Passa com 8-10 brinquedos. P.e.: colocar e tirar blocos de um recipiente; amassar e cortar papel ou juntar contas num colar e desmanchar.',
    'nv1_jog_06' : 'O jogo envolve a conclusão autônoma do objeto/atividade. Passa com 6-8 brinquedos. P.e.: abrir/fechar recipientes; colocar/tirar objetos, realizando diferentes ações com os mesmos.',
    'nv1_jog_07' : 'Ações socialmente convencionais e dirigidas para si. Podem ser em resposta ao modelo do adulto mas independentes, a utilização espontânea dos objetos é necessária em pelo menos uma ação. P.e.: colocar o telefone na orelha; escovar o cabelo com a escova; colocar o garfo/colher na boca; limpar o nariz com lenço; levar o copo aos lábios; colocar contas.',
    'nv1_jog_08' : 'Termina a atividade apropriadamente e mostra alguma tentativa de arrumar (p.e., guarda um objeto ou entrega para o adulto). Pode ser em resposta à sugestão verbal ou ao gesto do adulto para começar, mas precisa participar sem ajuda física.',
    #
    'nv1_mfi_01' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário colocar 1-2 formas autonomamente.',
    'nv1_mfi_02' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário colocar 2-3 anéis autonomamente.',
    'nv1_mfi_03' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário três ou mais peças autonomamente.',
    'nv1_mfi_04' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário colocar três ou mais pinos autonomamente.',
    'nv1_mfi_05' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas tem que apertar os botões autonomamente.',
    'nv1_mfi_06' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas tem de separar três ou mais peças ou legos autonomamente.',
    'nv1_mfi_07' : 'O adulto pode colocar o brinquedo ao alcance da criança mas sem outras facilidades.',
    'nv1_mfi_08' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário empilhar pelo menos três blocos ou copos autonomamente.',
    'nv1_mfi_09' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário segurar e fazer marcas autonomamente. As marcas não precisam ter uma forma reconhecível.',
    'nv1_mfi_10' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário segurar e bater no brinquedo autonomamente.',
    'nv1_mfi_11' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário segurar nos objetos e encher a colher/usar o balde/despejar autonomamente.',
    'nv1_mfi_12' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário empilhar pelo menos três peças autonomamente.',
    #
    'nv1_mgr_01' : 'Não pode agarrar o adulto ou objeto (mesa, cadeira) para chutar a bola. Mantém equilíbrio, não cai, pode ser desajeitado.',
    'nv1_mgr_02' : 'Pode segurar no corrimão ou dar a mão ao adulto, colocando os dois pés em cada degrau. Não pode colocar as mãos nem os joelhos nos degraus.',
    'nv1_mgr_03' : 'Deve fazer sem ajuda.',
    'nv1_mgr_04' : 'Deve fazer sem ajuda em brinquedos de montar, cavalo de balanço ou cadeiras para criança ou adulto.',
    'nv1_mgr_05' : 'Usa reações de proteção ou de equilíbrio (estica as mãos, estende os braços, protege a cabeça).',
    'nv1_mgr_06' : 'Mostra consciência do corpo em relação aos objetos passando por cima ou caminhando em redor dos objetos.',
    'nv1_mgr_07' : 'Deve fazer com ajuda e com orientação espacial para frente.',
    'nv1_mgr_08' : 'O adulto pode começar a rotina mas, a criança mostra interesse fazendo rolar o brinquedo em direção à pessoa.',
    #
    'nv1_com_01' : 'Comportamentos autoagressivos, agressão, birras frequentes e/ou graves.',
    'nv1_com_02' : 'Senta-se calmamente/feliz durante pelo menos 60 segundos, enquanto interage com o adulto.',
    'nv1_com_03' : 'Os jogos podem incluir "Cadê/Achou", canções ou rotinas físicas (cócegas, subir e descer do colo do adulto).',
    'nv1_com_04' : 'As solicitações dos adultos são dentro do conjunto das competências atuais da criança. As birras podem ocorrer mas sem comportamento agressivo.',
    'nv1_com_05' : 'Sem agressão ou outras interações inapropriadas observadas no relatório dos pais.',
    #
    'nv1_ipe_01' : 'Senta à mesa durante a refeição (não se levanta ou anda ou sai da mesa durante a refeição). Não precisa manter-se durante toda a refeição da família.',
    'nv1_ipe_02' : 'O adulto prepara a comida mas, não é preciso nenhum outro tipo de assistência.',
    'nv1_ipe_03' : 'Segura e coloca o copo na boca sem ajuda. É possível sorver um pouco de líquido enquanto bebe.',
    'nv1_ipe_04' : 'Segura e coloca a colher na boca sem ajuda na maioria das colheradas. Pode deixar cair ocasionalmente.',
    'nv1_ipe_05' : 'Segura e coloca o garfo na boca sem ajuda na maioria das dentadas. Pode deixar cair ocasionalmente.',
    'nv1_ipe_06' : 'O relatório dos pais é suficiente.',
    'nv1_ipe_07' : 'Permite que um alimento novo fique no prato e tenta comer (toca, cheira ou coloca na boca). Não tem que comer.',
    'nv1_ipe_08' : 'O adulto pode colocar o canudo na boca da criança se ela nunca tomou antes.',
    'nv1_ipe_09' : 'Não precisa desabotoar ou abrir o zíper das roupas, mas deve conseguir tirar itens com ajuda. P.e., o adulto tira os braços e a criança a cabeça da camiseta; o adulto desabotoa a calça e a criança tira.',
    'nv1_ipe_10' : 'Não precisa abotoar ou fechar o zíper das roupas, mas deve vestir um item com ajuda. P.e.: o adulto estica a camiseta e a criança passa a cabeça; segura o sapato e a criança coloca o pé; o adulto coloca os pés da calça e a criança sobre.',
    'nv1_ipe_11' : 'Pode ser ajudado, se necessário, mas é capaz de colocar as mãos debaixo da água durante pelo menos 5 segundos. O relatório dos pais é suficiente.',
    'nv1_ipe_12' : 'Pode ser ajudado, se necessário, mas usa uma toalha para secar ambas as mãos. O relatório dos pais é suficiente.',
    'nv1_ipe_13' : 'Pode ser ajudado, se necessário, mas usa uma toalha em muitas partes do corpo (p.e. rosto, mãos, barriga, pernas). O relatório dos pais é suficiente.',
    'nv1_ipe_14' : 'Pode fazer birra, mas é capaz de terminar a rotina sem agressividade ou problemas de autoagressão ou de comportamentos graves.',
    'nv1_ipe_15' : 'P.e.: segura a escova/pente, ou toma a vez.',
    'nv1_ipe_16' : 'Coloca a escova de dentes na boca, saboreia a pasta. Não tem que escovar os dentes.',
    'nv1_ipe_17' : 'Pode ser lembrado ou receber ajuda física se necessário (p.e. adulto entrega a roupa, aponta para o cesto), mas é capaz de colocar as roupas no cesto.',
    'nv1_ipe_18' : 'Pode ser lembrado ou receber ajuda física se necessário (p.e. adulto entrega o lenço, aponta o lixo), mas é capaz de jogar os lenços no lixo.',

    ##########

    'nv2_cre_01' : 'A criança responde a instruções verbais isoladas; para cada atividade por completo, olha para o adulto e espera a instrução.',
    'nv2_cre_02' : 'Responde a instruções verbais envolvendo verbos (p.e., balançar o chocalho, bater com paus, abraçar o bebê, bater na massinha, cortar, levantar, bater palmas, mexer nas orelhas; tem que seguir tanto as ações corporais como as com objetos.',
    'nv2_cre_03' : 'Para passar tem que identificar cinco ou mais partes do corpo.',
    'nv2_cre_04' : 'Autoexplicativo.',
    'nv2_cre_05' : 'Responde a “Onde está...?” ou Mostra-me...? com o dedo indicador e o olhar.',
    'nv2_cre_06' : 'Para passar a criança tem de demonstrar uma compreensão generalizada de três ou mais preposições seguindo instruções verbais usando objetos.',
    'nv2_cre_07' : 'Para passar tem de responder a quatro ou mais nome diferentes. Se a pessoa/animal de estimação chamado está presente, a criança deverá olhar claramente para a pessoa ou animal que foi chamado (também pode apontar). Em fotos, a criança deverá tocar ou apontar para a imagem nomeada.',
    'nv2_cre_08' : 'Em resposta à indicação verbal “Vai buscar...” a criança traz objetos da sala, mas fora do seu campo de visão. A tarefa envolve lembrar o pedido pelo tempo suficiente para realizar uma busca visual na sala e recuperar o objeto do chão, mesa, cadeira ou prateleira.',
    'nv2_cre_09' : 'Faz uma sequência de duas ações com um objeto em resposta a uma instrução verbal com o gesto. É preciso demonstrar três ou mais sequências diferentes para passar (p.e., “Vai buscar os sapatos e traga para mim”).',
    'nv2_cre_10' : 'Identifica cinco ou mais partes do corpo numa imagem grande ou num desenho quando solicitado',
    #
    'nv2_cex_01' : 'A criança combina o gesto e a vocalização específica ou uma aproximação da palavra para comunicar todas estas quatro funções.',
    'nv2_cex_02' : 'Produz cinco ou mais aproximações de palavras diferenciadas dentro de rotinas familiares. Estas podem ser espontâneas ou imitadas espontaneamente, mas não com ajuda.',
    'nv2_cex_03' : 'Produz três ou mais aproximações de palavras diferenciadas para verbos que envolvam ações em si mesmo com objetos – espontâneas ou por imitação, mas sem ajuda.',
    'nv2_cex_04' : 'Isto envolve aproximações de palavras usadas espontaneamente para solicitar ações ou objetos. Tanto as formas nominais como as não nominais devem ser usadas para passar.',
    'nv2_cex_05' : 'Passa se a criança nomeia cinco ou mais objetos e cinco ou mais imagens espontaneamente.',
    'nv2_cex_06' : 'Faz variações de entonação quando produz algumas palavras em músicas ou canções, demonstrando consciência dos padrões de entonação envolvidos.',
    'nv2_cex_07' : 'Usa rotineiramente palavras simples com o olhar para pedir, protestar, recusar e negar.',
    'nv2_cex_08' : 'Produz 10 ou mais verbos tanto por imitação como espontaneamente para nomear ações em si mesmo, nos outros ou com objetos.',
    'nv2_cex_09' : 'Nomeia pessoas no espelho, na vida real ou para obter atenção. Pode ser em resposta à pergunta “Quem é este?”.',
    'nv2_cex_10' : 'Combina espontaneamente o balançar da cabeça com a verbalização “Não” para recusar uma oferta.',
    'nv2_cex_11' : 'Combina espontaneamente o acenar da cabeça com a verbalização “Sim” para aceitar a oferta.',
    'nv2_cex_12' : 'Olha espontaneamente para o adulto e gesticula para o objeto, via gesto manual ou alternando o olhar enquanto pergunta, “O que é isso?” em vários contextos.',
    #
    'nv2_cac_01' : 'Autoexplicativo',
    'nv2_cac_02' : 'Autoexplicativo',
    'nv2_cac_03' : 'Isto envolve dar ou tirar espontaneamente. Se é para tirar, o adulto não deve oferecer o objeto. O olhar comunica o “pedido”.',
    'nv2_cac_04' : 'Autoexplicativo',
    'nv2_cac_05' : 'Envolve atos da rotina do mostrar, posicionando o objeto em direção ao rosto do adulto, olhando para o adulto esperando um comentário. Passa se isto é observado várias vezes no momento do jogo.',
    'nv2_cac_06' : 'Obtenha o contato visual da criança na interação face-a-face e, em seguida, volte-se para olhar para o objeto. Passe se a criança demonstrar a rotação da cabeça e alguma procura. Não precisa encontrar o objeto.',
    'nv2_cac_07' : 'Envolve rotinas de ações, várias por hora. A criança deve apontar para o alvo, olhar para o adulto e esperar por um comentário para passar.',
    'nv2_cac_08' : 'Trata-se de mudanças claras do olhar, do objeto para os olhos do adulto e voltar para o objeto para compartilhar satisfação. Deve ser observado várias vezes num jogo social de 10 minutos para passar.',
    #
    'nv2_cso_01' : 'A criança começa rotineiramente trocas comunicativas (de qualquer tipo) com olhar e mantém o olhar de forma natural ao longo da troca.',
    'nv2_cso_02' : 'Inicia e transmite olhares sociais através dos movimentos corporais, gestos ou padrões vocais que são específicos para umdeterminado jogo. Deve fazer sinalizações em três ou mais jogos para passar.',
    'nv2_cso_03' : 'Retribui espontânea e consistentemente abraços dos adultos familiares com os braços e o corpo, retribui beijos franzindo as bochechas ou os lábios.',
    'nv2_cso_04' : 'Procura o contato visual do adulto usando palavras ou gestos claros de qualquer tipo (acenar, mostrar, virar o rosto, bater, etc).',
    'nv2_cso_05' : 'Responde aos cumprimentos com palavras e gestos, sem ajuda.',
    'nv2_cso_06' : 'Inicia pedidos de ajuda usando tanto sinais convencionais como aproximações de palavras combinadas com o olhar. A manipulação das mãos e do corpo não conta, a menos que acompanhada pelo olhar e palavras apropriadas.',
    'nv2_cso_07' : 'Acompanha espontaneamente os atos comunicativos com o olhar.',
    'nv2_cso_08' : 'Brinca em vários jogos de roda e imita os movimentos de dança ao som de músicas.',
    'nv2_cso_09' : 'Persegue outras pessoas e apanha-a enquanto brinca de pega-a-pega, e também corre para não ser apanhada durante a brincadeira.',
    'nv2_cso_10' : 'Inicia espontaneamente jogos sociais familiares com um parceiro, estabelecendo contato visual e usando um gesto associado e o seu nome ou uma palavra de ação (p.e, “Cócegas”, Pega-pega”).',
    'nv2_cso_11' : 'Responde de forma consistente ao pedido verbal de um objeto por parte do par, olhando para ele e entregando-lhe o objeto.',
    'nv2_cso_12' : 'Participa em canções conhecidas e jogos sociais com padrões de movimento apropriados num ambiente de grupos pequenos (com mais 1-2 crianças) sem pistas especiais.',
    'nv2_cso_13' : 'Prossegue a atividade quando o par se junta, reconhecendo e aceitando a abordagem dos pares. Não “protege” os materiais nem rejeita a abordagem.',
    'nv2_cso_14' : 'Responde espontaneamente a um “Olá” e “Adeus” de um colega com o olhar, gesto e com as palavras apropriadas.',
    'nv2_cso_15' : 'Em situação de jogo paralelo, a criança responde rotineiramente às ofertas dos pares em trocas de vez, tanto dando o objeto quando solicitado como pedindo a sua vez, verbal e não-verbalmente, ambas as situações acompanhadas pelo olhar.',
    'nv2_cso_16' : 'Senta num pequeno grupo, sem cadeiras especiais ou ajuda do adulto, presta atenção ao adulto líder e segue as instruções verbais que estão dentro do seu repertório. O adulto pode usar o nome da criança para dar a instrução, mas nenhuma outra ajuda.',
    'nv2_cso_17' : 'Pega frequentemente num objeto, acompanhando com o olhar quando um colega oferece.',
    'nv2_cso_18' : 'Responde consistentemente e apropriadamente a pedidos de objetos em situações de pequenos grupos (p.e., momentos de rodas, mesa do lanche, mesa de trabalhos manuais, canto de jogos dramáticos).',
    'nv2_cso_19' : 'Durante as atividades de jogo paralelo, a criança imita algumas ações dos pares espontaneamente.',
    'nv2_cso_20' : 'Passa se conseguir revezar a vez com o parceiro e completar o jogo. Estas são as únicas competências necessárias para passar neste item.',
    #
    'nv2_imi_01' : 'Inclui quatro a cinco sons de vogais diferentes ou quatro a cinco sons de consoantes diferentes.',
    'nv2_imi_02' : 'Imita pelo menos cinco sons diferentes.',
    'nv2_imi_03' : 'Produz 10 ou mais aproximações de palavras.',
    'nv2_imi_04' : 'Estas são ações familiares; sem ajudas.',
    'nv2_imi_05' : 'Aproxima pelo menos cinco novas ações no primeiro modelo.',
    'nv2_imi_06' : 'Envolve imitar uma sequência de três ou mais ações relacionadas (p.e., tirar a tampa da caixa de encaixar; tirar as peças; colocar a tampa e introduzir peças).',
    'nv2_imi_07' : 'Imita consistentemente quatro ou mais ações naturalistas com miniaturas, em si mesmoe oferecendo ao parceiro.',
    'nv2_imi_08' : 'Imita consistentemente quatro ou mais ações dentro de uma música sem ajuda e se esperar.',
    'nv2_imi_09' : 'Imita consistentemente vários enunciados de duas palavras.',
    #
    'nv2_cog_01' : 'Corresponde e agrupa pelo menos cinco formas diferentes.',
    'nv2_cog_02' : 'Corresponde e agrupa pelo menos três tamanhos diferentes de objetos idênticos.',
    'nv2_cog_03' : 'Combina e classifica desenhos a lápis e padrões de desenhos.',
    'nv2_cog_04' : 'Combina e classifica objetos não idênticos por identidade (p.e., carros, cavalos, bolas, meias, sapatos, copos).',
    'nv2_cog_05' : 'Agrupa objetos por função: comer, vestir, brinca, desenhar.',
    'nv2_cog_06' : 'Reconhece quando um objeto de um conjunto está faltando e pergunta por ele ou o procura (p.e., uma peça de um puzzle perdida, um sapato que falta, um copo).',
    'nv2_cog_07' : 'Corresponde/classifica objetos pela cor e forma, ou forma e tamanho, etc.',
    'nv2_cog_08' : 'Combina uma variedade de objetos em grupos de quantidade envolvendo quantidades de um a três (p.e., peças de dominó, bolachas de animais num prato).',
    #
    'nv2_jog_01' : 'A criança demonstra consciência das relações funcionais de vários conjuntos de objetos no seu jogo e ao arrumar.',
    'nv2_jog_02' : 'Passa se fizer cinco ou mais sons destes durante o jogo.',
    'nv2_jog_03' : 'Requer ações espontâneas; não passa apenas com a imitação.',
    'nv2_jog_04' : 'Requer ações espontâneas que envolvam pelo menos duas ações relacionadas numa sequência. Não passa apenas com imitação.',
    'nv2_jog_05' : 'Passa se demonstrar consistentemente a abordagem de tentativa e erro na resolução de problemas no jogo com objetos.',
    'nv2_jog_06' : 'O adulto pode preparar vários conjuntos de materiais de construção ou visoespaciais, mas a criança tem de brincar sozinha usando durante o jogo uma maioria de ações apropriadas, sem mais do que duas interações verbais, para passar este item. Não penalize se alguns atos repetitivos ou estereotipados acontecerem dentro de um jogo apropriado.',
    'nv2_jog_07' : 'O adulto pode preparar algum material (massinha, arte, livros, adereços de jogo), mas a criança precisa brincar sozinha usando durante o jogo uma maioria de ações apropriadas, sem mais do que duas interações verbais, para passar este item. Não penalize se alguns atos repetitivos ou estereotipados acontecerem dentro de um jogo apropriado.',
    'nv2_jog_08' : 'Brinca de forma autônoma, incluindo ir buscar os materiais, deslocar-se para um espaço de jogo, arrumar e afastar os materiais no final. Isto pode envolver atividades ilimitadas ou limitadas.',
    #
    'nv2_mfi_01' : 'A criança completa o jogo de encaixe de forma autônoma; pode usar a tentativa e erro mas, sem instruções ou apoio de qualquer tipo.',
    'nv2_mfi_02' : 'Constrói de forma autônoma uma torre de 8-10 blocos que balança.',
    'nv2_mfi_03' : 'A criança copia várias construções diferentes envolvendo pelo menos três blocos (p.e., torre vertical, linha horizontal, ponte).',
    'nv2_mfi_04' : 'A criança usa vários tipos de objetos de encaixe e reúne cinco ou mais peças de várias formas.',
    'nv2_mfi_05' : 'Autoexplicativo.',
    'nv2_mfi_06' : 'O adulto pode ter que descolar um canto para que a criança entenda, mas a criança tira o auto-colante da folha adesiva e coloca-o sobre uma folha de forma autônoma.',
    'nv2_mfi_07' : 'Isto não é um teste de força – as tampas devem ser fáceis de remover.',
    'nv2_mfi_08' : 'Consegue abrir o fecho até o fim; a criança consegue puxar o fecho todo para cima, embora o adulto tenha que juntar as duas peças à criança.',
    'nv2_mfi_09' : 'Ata cinco ou mais contas, pedaços de massa, anéis, etc., até fazer uma sequência, sem ajuda.',
    'nv2_mfi_10' : 'Imita pelo menos três tipos de ações com ferramentas escritas.',
    'nv2_mfi_11' : 'Pode usar tesouras de crianças ou adulto. O adulto pode mostrar como se usa a tesoura, mas a criança corta de forma autónoma. Não é preciso segurar perfeitamente na tesoura. Deve fazer três cortes.',
    'nv2_mfi_12' : 'Pega de forma autônoma em cinco ou mais peças da mesa e coloca cada uma na ranhura, tanto na horizontal como na vertical, sem ajudas ou lembretes, e é bem sucedida com moedas de uma centímetro.',
    'nv2_mfi_13' : 'Consegue atar vários objetos com vários tipos de fios.',
    'nv2_mfi_14' : 'Completa o puzzle de forma autônoma, pode usar a tentativa e erro, mas sem instruções ou apoio.',
    #
    'nv2_mgr_01' : 'A criança imita ações de motricidade grossa consistentemente e de forma espontânea (pode ser instruída), independentemente da localização. Podem ser aproximações. É a consistência que é importante e não a precisão.',
    'nv2_mgr_02' : 'Pula e move-se no espaço, a partir de um degrau baixo até o solo, assim como a partir do solo.',
    'nv2_mgr_03' : 'Inicia de forma consistente ações apropriadas em vária peças de equipamento do parque infantil.',
    'nv2_mgr_04' : 'Senta sozinha no triciclo, na posição correta e tenta pedalar, mas pode precisar de ajuda para o fazer.',
    'nv2_mgr_05' : 'Manuseia autonomamente um carrinho ou carrinho de mão para mover as coisas no parque infantil.',
    'nv2_mgr_06' : 'Chuta uma bola grande com direcionalidade.',
    'nv2_mgr_07' : 'Cava com a pá, apanha a matéria e deposita-a de forma independente, em múltiplas pazadas.',
    #
    'nv2_ipe_01' : 'Quando instruída, mas sem ajuda, a criança pega no guardanapo e limpa a parte do corpo adequada de acordo com a instrução. Não tem de ser completo, mas tem que ser mais do que superficial.',
    'nv2_ipe_02' : 'Quando o adulto segura ou aproxima a travessa ou o prato da criança, esta usa o utensílio apropriado para servir os alimentos para o seu prato de forma autónoma. Pode ser desajeitada. O adulto pode indicar as quantidades.',
    'nv2_ipe_03' : 'Na mesa, quando alguém pede à criança para passar um item, a criança procura o item, pega nele, e passa-o à pessoa à esquerda ou à direita. A criança deve responder ao pedido através da procura do objeto e tentar agarrá-lo sozinha. Se alguém passar um recipiente à criança e instruí-la para passar à próxima pessoa, a criança segue a instrução sem ajudas.',
    'nv2_ipe_04' : 'Quando a criança sai da mesa, segue as instruções dos adultos para levar os itens especificados para um lugar específico, sem ajudas.',
    'nv2_ipe_05' : 'Senta durante toda a refeição e mantém-se no lugar sem ajudas ou outros apoios até que tenha terminado de comer e o adulto diga que pode sair.',
    'nv2_ipe_06' : 'Participa em todas as etapas de uma refeição de fast food – esperar, pedir, transportar, comer, limpar e sair, sem a necessidade de ajudas físicas completas. A criança caminha voluntariamente com os adultos até a porta ou mesa. Não precisa dar a mão para ficar com o adulto.',
    'nv2_ipe_07' : 'Responde voluntariamente à instrução de provar, mordiscar ou beber um alimento/bebida familiar.',
    'nv2_ipe_08' : 'Come algumas peças de fruta/verduras, lacticínios, cereais e carnes (a menos que existam restrições alimentares), espontaneamente.',
    'nv2_ipe_09' : 'Vai buscar espontaneamente o copo e tirar a água da torneira, prateleira ou da porta da geladeira, sem qualquer instrução ou ajuda do adulto. Se a criança usar a torneira, deve fechar a água espontaneamente.',
    'nv2_ipe_10' : 'Quando instruída, a criança tira a camisa, as calças, a roupa interior, as meias e os sapatos, sem ajuda a não ser para os fechos e coloca toda a roupa num recipiente apropriado. A criança pode ser verbal ou gestualmente relembrada uma ou duas vezes em toda a rotina, mas sem ajudas físicas, sejam totais ou parciais.',
    'nv2_ipe_11' : 'Autoexplicativo.',
    'nv2_ipe_12' : 'Tirar o casaco e a touca de forma autónoma; pode ser solicitado para colocar no cabide.',
    'nv2_ipe_13' : 'Depois de o adulto lhe dar um pano úmido e após a instrução “Lava o rosto”, a criança esfrega toda a superfície do rosto sem mais ajudas e afasta o pano ou pousa-o quando termina.',
    'nv2_ipe_14' : 'Quando instruída para assoar ou limpar o nariz, a criança dirige-se consistentemente para a caixa dos lenços, assoa ou limpa o nariz e deita o lenço fora, sem mais do que uma ajuda verbal e sem ajudas manuais.',
    'nv2_ipe_15' : 'Realiza consistentemente a ação manual para cada etapa da lavagem de mãos, exceto abrir a torneira, sem precisar de ajudas físicas completas. O adulto pode ajudar em alguns passos através do gesto ou de ajudas físicas parciais.',
    'nv2_ipe_16' : 'Não briga, não chora nem protesta de nenhuma outra forma durante a lavagem e o corte de cabelo. Participa, ajudando a esfregar o shampoo e usar a toalha. Pode usar reforços fortes durante a rotina.',
    'nv2_ipe_17' : 'Autoexplicativo – para brinquedos de banho convencionais.',
    'nv2_ipe_18' : 'Guarda rotineiramente os brinquedos do banho no recipiente apropriado sem mais ajudas após a instrução inicial, para passar.',
    'nv2_ipe_19' : 'Ajuda os pais a pôr a loção nas mãos, braços, pernas, barriga.',
    'nv2_ipe_20' : 'Esfrega a escova de dentes inferiores e superiores, à frente e atrás, quando instruída. Todos os níveis de ajudas físicas completas podem ser usados.',
    'nv2_ipe_21' : 'Dorme rotineiramente na própria cama e dorme sem a presença de um adulto no quarto depois de terminada a rotina de deitar e as luzes estarem desligadas. Raramente sai da cama ou do quarto depois de ter sido colocada na cama.',
    'nv2_ipe_22' : 'Demonstra consciência da rotina de deitar ao iniciar uma ou mais atividades, e participando nas várias etapas da rotina sem necessidades de ajudas completas.',
    'nv2_ipe_23' : 'O adulto pode preparar a situação, mas após a preparação e a instrução inicial, a criança leva até 20 talheres da máquina de lavar louça e coloca-os na gaveta dos talheres sem qualquer ajuda do adulto.',
    'nv2_ipe_24' : 'Quando o adulto abre a porta da máquina de secar e entrega o cesto da roupa, a criança tira todas as peças da máquina para o cesto sem necessidade de obter instruções. Pode precisar de ajuda com as peças mais difíceis.',
    'nv2_ipe_25' : 'A partir de um conjunto de 10 meias ou mais num cesto ou pilha, a criança emparelha, dobra ou junta as meias, e empilha-as num recipiente.',
    'nv2_ipe_26' : 'O adulto pode fornecer os materiais ou instruções diretas, mas a criança realiza a ação sem mais ajudas.',

    ##########

    'nv3_cre_01' : 'Fica com o adulto, presta atenção plena e participa da história que o adulto está lendo. Os exemplos incluem alternar o contato visual entre as páginas do livro e a adulto, apontando para as imagens do livro, virando as páginas e vocalizando os nomes das imagens do livro.',
    'nv3_cre_02' : 'Completa uma instrução olhando para o adulto e realizando a ação sem gestos ou ajuda física do adulto. O adulto pode repetir as instruções num segundo momento mas sem pista gestual.',
    'nv3_cre_03' : 'Identifica 50 ou mais objetos comuns para passar.',
    'nv3_cre_04' : 'Usa “Sim/Não” apropriadamente em contextos de pedido e recusa. Deve incluir o contato visual, embora não precise de ser acompanhado por gestos (ou seja, acenar/abanar a cabeça). Pode usar frases cordiais, “Sim, por favor”, “Não, obrigado”.',
    'nv3_cre_05' : 'Vocaliza ou gesticula (p.e., aponta) em resposta a perguntas do adulto. P.e.:“Mostra-me o bebê dormindo” ou “Cadê o cachorro correndo”. A resposta não precisa ser acompanhada do contato visual.',
    'nv3_cre_06' : 'Consistentemente segue duas ou três partes das instruções da rotina envolvendo ações e objetos em rotinas bem praticadas.',
    'nv3_cre_07' : 'Exemplos disto são usar os conceitos de forma adequada quando lhe é pedido (“Põe a bola ao lado do carro”, ou “Põe a bola debaixo da mesa”).',
    'nv3_cre_08' : 'Vocaliza ou gesticula (p.e., aponta, entrega os objetos) em resposta às perguntas do adulto. Alguns exemplos são: “Onde está a bola grande?” ou “Mostra-me o carro pequeno”. A resposta não precisa ser acompanhada do contato visual.',
    'nv3_cre_09' : 'Vocaliza ou gesticula (p.e., aponta, entrega os objetos) em resposta às perguntas do adulto. Alguns exemplos são: “Qual é o lápis azul?” ou “Mostra-me o caminhão vermelho”. A resposta não precisa ser acompanhada do contato visual.',
    'nv3_cre_10' : 'Vocaliza ou gesticula (p.e., aponta, entrega os objetos) em resposta às perguntas do adulto. Alguns exemplos são: “Que animal faz miau?” ou “O que faz o cachorro?”, ou “O que você ouviu?”. A resposta não precisa ser acompanhada do contato visual.',
    'nv3_cre_11' : 'Vocaliza ou gesticula (p.e., aponta, entrega os objetos) em resposta às perguntas do adulto. Alguns exemplos são: “O que usamos para pedalar?” ou “O que usamos para beber?”. A resposta não precisa ser acompanhada do contato visual. Identifica três ou mais funções de objetos para passar.',
    'nv3_cre_12' : 'Vocaliza ou gesticula (p.e., aponta, entrega os objetos) em resposta às perguntas do adulto. Alguns exemplos são: “De quem é a vez?” ou “De quem é esse sapato?”. A resposta não precisa ser acompanhada do contato visual.',
    'nv3_cre_13' : 'Vocaliza ou gesticula (p.e., aponta, entrega os objetos) em resposta às perguntas do adulto. Alguns exemplos são: “Mostra-me como joga bola” ou “Mostra-me o porco come”. A resposta não precisa ser acompanhada do contato visual.',
    'nv3_cre_14' : 'Completa a instrução, olhando para o adulto e a realizando a ação sem gestos ou ajuda física do adulto. O adulto pode repetir a instrução um segundo momento, sem pista gestual. P.e.: “Dá o carro e fecha o livro” ou “Põe a bola no balde e a boneca em cima da mesa”.',
    #
    'nv3_cex_01' : 'As verbalizações devem incluir o contato visual. Ex: “Quer mais suco?”, “Tchau, ...”, “Ajuda a abrir” ou “Bola não”. A articulação não precisa ser perfeita.',
    'nv3_cex_02' : 'As verbalizações devem incluir o contato visual e não estão relacionadas com pedidos para comentar objetos ou ações. Ex.: “Olha a vaca”, “Avião anda rápido” ou “Cãozinho”. A articulação não precisa ser perfeita.',
    'nv3_cex_03' : 'As verbalizações não precisam ser acompanhadas por contato visual. Ex.: “Bebê comer” ou “Pássaro voar”. A articulação pode não ser perfeita.',
    'nv3_cex_04' : 'As verbalizações devem incluir o contato visual. Ex.: “Coelho em cima da cadeira” ou “Bola dentro...”. A articulação pode não ser perfeita.',
    'nv3_cex_05' : 'As verbalizações devem incluir o contato visual. O adulto pode usar um objeto pertencente à criança. Ex.: “Isso (copo com canudo) é meu” ou “Tua vez”, “Meu bebê. A articulação pode não ser perfeita.',
    'nv3_cex_06' : 'A verbalização ou gesto (p.e., encolher os ombros, levantar as mãos) devem incluir o contato visual.',
    'nv3_cex_07' : 'A verbalização deve incluir o contato visual. A articulação pode não ser perfeita.',
    'nv3_cex_08' : 'A verbalização deve incluir o contato visual. Ex.: “Vai dizer olá à mamãe” ou “Diz para o papai vir aqui”. A articulação pode não ser perfeita.',
    'nv3_cex_09' : 'A verbalização deve incluir o contato visual.',
    'nv3_cex_10' : 'A verbalização deve incluir o contato visual. O adulto pode querer usar um espelho para testar. A resposta pode incluir as variantes do eu e tu. Ex.: “Este sou eu” ou “Eu te vejo”.',
    'nv3_cex_11' : 'A verbalização e/ou gestos (p.e. representar) devem incluir o contato visual. A criança pode usar palavras ou frases simples. Ex.: “Cãozinho”, “Pega a bola” ou “Sobe balão”. A articulação não precisa ser perfeita.',
    'nv3_cex_12' : 'A verbalização não precisa ser acompanhada por contato visual. O adulto pode perguntar, “Qual é a cor do carro?”, mas a criança deve iniciar a resposta (“Carro vermelho”, “É um balão azul”). A aproximação pode ser aceita.',
    'nv3_cex_13' : 'A verbalização não precisa ser acompanhada por contato visual. O adulto pode perguntar uma segunda vez.',
    'nv3_cex_14' : 'A verbalização não precisa ser acompanhada por contato visual. O adulto pode perguntar uma segunda vez.',
    'nv3_cex_15' : 'A verbalização não precisa ser acompanhada por contato visual. O adulto pode perguntar uma segunda vez.',
    'nv3_cex_16' : 'A verbalização não precisa ser acompanhada por contato visual. A pergunta pode ser um enunciado de uma palavra com a entonação ascendente. Ex.: “Biscoito?” ou “Vamos embora?”.',
    'nv3_cex_17' : 'A verbalização não precisa ser acompanhada por contato visual. Deve fazer as duas perguntas para passar.',
    'nv3_cex_18' : 'A verbalização não precisa ser acompanhada por contato visual. Ex.: “Qual é seu nome?”, “Quantos anos você tem?”, “Qual é a cor da sua camiseta?”.',
    #
    'nv3_cso_01' : 'Participa duas ou mais vezes em qualquer comportamento ativo (alcançar, imitar vocalizar) em três ou mais jogos. O contato visual e os sorrisos não são suficientes. Ex.: “Escondidas”, “Ring-around-the-Rosy”, e jogar a bola.',
    'nv3_cso_02' : 'Responde até 3 segundos após o pedido do parceiro. O parceiro pode repetir uma segunda vez. A resposta pode incluir a verbalização (p.e. “bebe”) ou um gesto (p.e. traz o objeto ao par e mantém na mão).',
    'nv3_cso_03' : 'Participa duas ou mais vezes em qualquer comportamento ativo em duas ou mais rotinas. O contato visual e os gestos isolados não são suficientes. Ex.: “Dedos assustadores”, “Cócegas”.',
    'nv3_cso_04' : 'O relatório dos pais pode ser aceito. Ex.: “Traz a bola”, “Você é a mamãe” ou “Põe isso ali”.',
    'nv3_cso_05' : 'O relatório dos pais pode ser aceito. Inicia/imita duas ou mais rondas em três ou mais jogos apropriados à idade (p.e., “Apanhada”, “Escondidas”, brincar com trens, mascarar-se).',
    'nv3_cso_06' : 'O relatório dos pais pode ser aceito. Participa em duas ou mais tomadas de vez. Os comportamentos podem incluir verbalizações (p.e. “Bebê está com fome”), imitação, ou observação do jogo do parceiro. Ex.: brincar de casinha, se fantasiar, dramatizar.',
    'nv3_cso_07' : 'Participa em duas ou mais rondas em três ou mais jogos apropriados.',
    'nv3_cso_08' : 'Usa de forma espontânea e adequada. As aproximações podem ser aceitas. Passa se usar frequentemente dois dos três.',
    'nv3_cso_09' : 'Ex.: “Seu mestre mandou”, fingir que se move como um animal. Imita espontaneamente 10 ou mais ações novas. Pode ser impreciso.',
    'nv3_cso_10' : 'Participa em 3 ou mais atividades com comportamentos ativos (verbaliza, representa, imita). O contato visual e o sorriso por si só não são suficientes. Ex.: brincadeira de casinha, professor, deitar bebê na cama.',
    'nv3_cso_11' : 'Inicia comportamentos, três ou mais vezes, com contato visual. Ex.: Verbalizações (“Mamãe, olha o gatinho”, “Blocos caíram”, “Mais biscoito, papai”) com gestos (p.e., dar ou entregar o objeto ao adulto, apontar para um objeto).',
    'nv3_cso_12' : 'Responde no espaço de três segundos após a incitação do adulto. O adulto pode repetir uma segunda vez.',
    'nv3_cso_13' : 'Responde no espaço de três segundos após a incitação do adulto. O adulto pode repetir uma segunda vez. Identifica dois ou mais sentimentos afetivos (p.e., feliz, triste, bravo, assustado, surpreso). A verbalização não precisa ser acompanhada do contato visual.',
    'nv3_cso_14' : 'Identifica dois ou mais sentimentos afetivos (p.e., feliz, triste, bravo, assustado, surpreso). A verbalização não precisa ser acompanhada do contato visual.',
    'nv3_cso_15' : 'Identifica dois ou mais sentimentos afetivos (p.e., feliz, triste, bravo, assustado, surpreso). A verbalização não precisa ser acompanhada do contato visual.',
    # 
    'nv3_cog_01' : 'Faz correspondência de todas as letras do primeiro nome.',
    'nv3_cog_02' : 'Faz correspondência de cinco ou mais letras. Pode ser em resposta à sugestão verbal do adulto (p.e., “Onde está o A?”) ou com demonstração nas primeiras tentativas, mas a criança tem de fazer correspondência de forma autônoma em pelo menos cinco tentativas.',
    'nv3_cog_03' : 'Faz correspondência de cinco ou mais palavras. Pode ser em resposta à sugestão verbal do adulto (p.e., “Onde está o g-a-t-o?”) ou com demonstração nas primeiras tentativas, mas a criança tem de fazer correspondência de forma autônoma em pelo menos cinco tentativas.',
    'nv3_cog_04' : 'Faz correspondência de cinco ou mais números. Pode ser em resposta à sugestão verbal do adulto (p.e., “Onde está o 6?”) ou com demonstração nas primeiras tentativas, mas a criança tem de fazer correspondência de forma autônoma em pelo menos cinco tentativas.',
    'nv3_cog_05' : 'Identifica cinco ou mais em cada categoria. Pode ser em resposta à sugestão verbal do adulto (p.e., “Onde está o 6?”, “Mostra o lápis azul” ou “Qual letra?”) ou com demonstração nas primeiras tentativas, mas a criança tem de fazer correspondência de forma autônoma em pelo menos cinco tentativas.',
    'nv3_cog_06' : 'Identifica três ou mais objetos escondidos.O adulto pode sondar mostrando três objetos à criança (p.e., uma moeda, uma bola pequena e um pauzinho) e em seguida, coloca um copo sobre cada item. O adulto espera 7 segundos e em seguida, mostra uma réplica de um dos objetos escondidos (p.e., a bola pequena) e pergunta: “Onde está a outra bola?”. A resposta pode ser a verbalização (“Não”) e/ou gesto (p.e. apontar, pegar o copo). O contato visual não é necessário. O adulto deve preparar três ou mais tentativas.',
    'nv3_cog_07' : 'Deverá classificar em conjuntos de três, oito classes de objetos.',
    'nv3_cog_08' : 'Compreende relações tanto verbalmente (p.e., conta cinco objetos) como gestualmente (p.e. toca ou agrupa cinco objetos).',
    'nv3_cog_09' : 'Atribui valor a cinco ou mais objetos. O adulto pode ter que contar os objetos preferidos da criança, como damas, doces, trens ou blocos. O adulto pode começar contando o primeiro item, mas a criança precisa continuar e terminar de forma autônoma.',
    'nv3_cog_10' : 'Pode ser em resposta à sugestão verbal do adulto (p.e., “O que vem a seguir?”). a criança deverá sequenciar de forma independente e narrar quando lhe for perguntado, “Conta lá” em três ou mais sequencias diferentes.',
    #
    'nv3_jog_01' : 'Constrói três ou mais esquemas. Os vários objetos podem ser caminhões na estrada, blocos para construir, contas para fazer um colar.',
    'nv3_jog_02' : 'Ex.: construir uma pista, empurrar os trens e bater os trens; tirar massinha, usar o cortador de formas e tirar a forma. (Nota: estes podem formar a sequência da imagem durante 10 vezes isoladas).',
    'nv3_jog_03' : 'Ex: Fingir que entorna o suco e alimenta o bebê; pegar o cobertor e deitar a boneca na cama; pôr o animal no carro empurrando-o.',
    'nv3_jog_04' : 'Põe as figuras em contexto apropriado durante o jogo. Ex: sentar o pai na cadeira para ver TV ou colocar a mãe no carro para dirigir até a loja.',
    'nv3_jog_05' : 'Completa três ou mais ações sem ajuda do adulto.',
    'nv3_jog_06' : 'Organiza duas ou mais ajudas em três ou mais esquemas de jogo diferentes. Ex.: dispor o garfo e o prato para alimentar o bebê; colocar o chapéu em si mesmo e nos outros para o jogo de mascarar.',
    #
    'nv3_mfi_01' : 'Autoexplicativo.',
    'nv3_mfi_02' : 'Imita cada um, pelo menos uma vez. O adulto modela e pode usar sugestões verbais (p.e., “Desenha isto”).',
    'nv3_mfi_03' : 'Usa cinco ou mais blocos para construir três ou mais estruturas diferentes.',
    'nv3_mfi_04' : 'Lança através de três ou mais laçadas/buracos. O adulto pode usar a pista verbal (p.e., “Põe ali”) ou demonstrar na primeira tentativa.',
    'nv3_mfi_05' : 'Traça pelo menos três quartos de uma linha e uma curva com o dedo e com o material de escrita. O adulto pode modelar na primeira tentativa.',
    'nv3_mfi_06' : 'Usa dois ou mais dedos utensílios para pegar e soltar dois ou mais objetos. Ex.: usar uma colher grande para pegar/largar um pedaço de comida ou pinças para pegar e soltar blocos.',
    'nv3_mfi_07' : 'Traça três ou mais formas (p.e., quadrado, círculo, triângulo e retângulo). Pode usar uma armação de plástico ou as linhas pautadas no papel.',
    'nv3_mfi_08' : 'O corte não precisa seguir uma linha, mas tem que cortar uma tira de papel em dois. O adulto pode mostrar como segurar a tesoura e cortar ao longo do papel.',
    'nv3_mfi_09' : 'Corta ao longo da linha com bastante precisão. O adulto pode modelar na primeira tentativa.',
    'nv3_mfi_10' : 'O adulto pode usar a pista verbal (p.e., “Primeiro faz isto, depois faz isto”) ou demonstrar os passos na primeira tentativa.',
    'nv3_mfi_11' : 'Realiza três ou mais esquemas. Usa duas ou mais ferramentas para passar. Ex.: enrolar massinha e cortar com uma faca; ou fazer uma bola de massinha e fingir que come com o garfo.',
    #
    'nv3_mgr_01' : 'Pedala e conduz, segue uma rota de forma autônoma e com uma boa coordenação.',
    'nv3_mgr_02' : 'Chuta sem se agarrar a um objeto/pessoa. Não tropeça nem cai. Faz contato três ou mais vezes.',
    'nv3_mgr_03' : 'Sobe e usa equipamentos do parque infantil simples (p.e. balanço, escorregadores pequenos) e equipamentos mais complexos (p.e. jungle gyms, barras para escalar, escorregadores grandes). Pode segurar nas grades.',
    'nv3_mgr_04' : 'Joga pelo menos durante 5 minutos.',
    'nv3_mgr_05' : 'Imita cinco ou mais ações em três ou mais canções diferentes. Ex: imitação dos movimentos corporais em “Se você está contente...” ou “A rodas do ônibus...”. As imitações são espontâneas e imediatas.',
    'nv3_mgr_06' : 'Faz lançamentos dissimulados três ou mais vezes. Não tem que acertar o alvo completamente. O adulto pode demonstrar até duas tentativas.',
    'nv3_mgr_07' : 'Salta para frente três ou mais vezes.',
    'nv3_mgr_08' : 'Salta com um pé só pelo menos uma vez. Pode saltar agarrado a uma pessoa ou objeto estável, sem cair.',
    #
    'nv3_ipe_01' : 'Não precisa segurar a colher e o copo corretamente.',
    'nv3_ipe_02' : 'A família é capaz de comer toda a refeição sem problemas graves de comportamento (p.e., atirar objetos, bater, rastejar debaixo da mesa, fugir). A criança pode fazer barulho ocasionalmente, mas pode ser direcionada para atividades que ocupem a sua atenção (p.e., desenhar, brincar com brinquedos pequenos).',
    'nv3_ipe_03' : 'Encontra o ícone/imagem/símbolo no livro, seleciona o ícone apropriado e completa a escolha de uma atividade sem ajuda. Conclui de forma autônoma, pelo menos 80% das vezes, em casa e na escola. Se nenhum destes for usado pela criança, passe o item.',
    'nv3_ipe_04' : 'Leva pelo menos um material sozinho. Ex.: mochila, lancheira, casaco, etc.',
    'nv3_ipe_05' : 'Introduz/remove pelo menos três objetos sozinha mediante pedido. Ex.: lancheira, caderno, brinquedo, etc.',
    'nv3_ipe_06' : 'Abre zíper, botões de forma autônoma.',
    'nv3_ipe_07' : 'Pode pedir ajuda na lavagem das mãos se não alcançar o lavatório.',
    'nv3_ipe_08' : 'Puxa para cima e para baixo a cueca/calcinha e calça. O adulto pode segurar a peça de roupa para a criança “enfiar” (se tiver sido retirada), mas a criança puxa para baixo/cima sozinha.',
    'nv3_ipe_09' : 'Abre e fecha a torneira, usa sabão, esfrega e seca as mãos. Pode ser lembrada.',
    'nv3_ipe_10' : 'Autoexplicativo. Pode ser lembrada.',
    'nv3_ipe_11' : 'Autoexplicativo. Pode ser lembrada.',
    'nv3_ipe_12' : 'Tapa a boca com a mão ou lenço. Pode ser lembrada.',
    'nv3_ipe_13' : 'O adulto pode fornecer a toalha, sabonete, esponja ou colocar o sabonete na esponja, mas a criança ajuda na lavagem e secagem do corpo (p.e., rosto, barriga, braços, pernas).',
    'nv3_ipe_14' : 'Escova para cima/baixo pelo menos cinco ou mais vezes nos dentes de cima e de baixo. O adulto pode colocar a pasta na escova de dentes. Pode-lhe ser dito para continuar a escovar.',
    'nv3_ipe_15' : 'Coloca alimentos/água na taça e traz para o animal de estimação. O adulto pode ajudar (p.e., abrir a lata, medir quantidades) ou lembrar.',
    'nv3_ipe_16' : 'Leva pelo menos dois ou mais itens (p.e. prato, copo, tigela, etc) para a máquina de lavar. Pode ser lembrada.',
    'nv3_ipe_17' : 'Retira cinco ou mais itens. O adulto pode mostrar onde se coloca o item. Leva pelo menos dois ou mais itens (p.e. prato, copo, tigela, etc) da máquina. Pode ser lembrada.',
    'nv3_ipe_18' : 'Guarda três ou mais peças de roupa cuidadosamente dobradas na gaveta, mas não precisa dobrá-las. Pode ser lembrada.',
    'nv3_ipe_19' : 'Agarra em bens pessoais (p.e, roupas, brinquedos, sapatos, etc) e coloca-os num local apropriado quando solicitado. Pode ser lembrada.',

    ##########

    'nv4_cre_01' : 'Pega, dá, aponta ou mostra o item correto ao adulto numa escolha de dois objetos. A criança identifica cinco conceitos diferentes corretamente. Ex.: quente/frio, vazio/cheio,molhado/seco, duro/mole, pesado/leve, alto/baixo/longo, grande/pequeno.',
    'nv4_cre_02' : 'Pega, dá, aponta ou mostra o item correto ao adulto. Ex.: “Me dá o lápis azul, quebrado” e a criança faz referência ao item correto.',
    'nv4_cre_03' : 'Pega, dá, aponta ou mostra personagens, figuras ou pessoas reais femininas ou masculinas corretamente em resposta a instruções que envolvem “a ele ou a ela”. Ex.: “coloca-o no carro ou “Ela quer um pouco de sorvete”. A criança deve passar em pelo menos um pronome de gênero masculino e feminino para passar está competência.',
    'nv4_cre_04' : 'Pega, dá, aponta ou mostra o item correto ao adulto num campo de quatro ou cinco escolhas. Para passar, a criança deve compreender três ou mais conjuntos comparativos.',
    'nv4_cre_05' : 'A criança demonstra compreensão desses conceitos ao colocar os objetos na posição solicitada ou olhando para o local correto quando sugerido (p.e., “Procura atrás do sofá).',
    'nv4_cre_06' : 'Pega, dá, aponta ou mostra o item correto que identifica a ausência de um objeto (tigela sem cereais)ou características (criança que não tem olhos azuis) ou uma ação que não está acontecendo (aquele que não está dormindo).',
    'nv4_cre_07' : 'Em objetos e imagens, a criança aponta ou mostra a parte de um item quando solicitado (p.e., o nariz do coelhinho, a roda da bicicleta, a porta do carro).',
    'nv4_cre_08' : 'Escuta histórias simples quando estas são lidas (cinco páginas). Demonstra atenção, olhando para o livro e para o adulto respondendo de forma precisa as questões, verbalmente ou apontando, página por página. Responde a duas ou três questões no final.',
    'nv4_cre_09' : 'Responde corretamente ao verbalizar, sacudir ou acenar com a cabeça quando o adulto pergunta: “Isto é um...?” “O seu nome é Sam?”.',
    'nv4_cre_10' : 'Responde corretamente com a frase à pergunta “O que faria se estivesse cansado, ou com fome, ou com sede?). Para quatro ou mais: magoada, cansado, com fome, com sede.',
    'nv4_cre_11' : 'Responde corretamente a três ou mais informações pessoais. Ex.: “Qual é o seu nome completo?”, “Qual é seu número de telefone?”, “Qual é seu endereço?”.',
    'nv4_cre_12' : 'Pega, dá, aponta ou mostra imagens /itens para instruções que envolvam encontrar objetos que são iguais e que são diferentes.',
    'nv4_cre_13' : 'Pega, dá, aponta ou mostra imagens /itens corretamente em resposta a perguntas de quantidade: um, alguns, todos, poucos, a maioria. Deve passar em todos para passar nesta competência.',
    'nv4_cre_14' : 'Pega, dá, aponta ou mostra o item com característica que o adulto indica. Ex.: o adulto diz “Me mostra o cachorro com o rabo comprido” e a criança indica a resposta correta. As características envolvem tamanho, forma, textura, estado físico. Passar requer a compreensão de 10-15 características.',
    'nv4_cre_15' : 'Entende categorias de objetos que envolvam cor, forma, tamanho ou função: os azuis, os redondos, os grandes, os que são para comer.',
    'nv4_cre_16' : 'Deve responder com precisão ao passado e ao futuro, quer nos verbos regulares ou irregulares.',
    'nv4_cre_17' : 'Demonstra compreensão da voz passiva através da manipulação dos objetos ou da seleção de imagens (p.e., “O cachorro foi atingido pela bola” ou “A menina foi perseguida pelo menino”.',
    'nv4_cre_18' : 'Responde com precisão a questões que envolvam estas três relações temporais: primeiro/último, antes/depois, ao mesmo tempo.',
    'nv4_cre_19' : 'Age em conformidade com a solicitação do adulto que contém três ou mais componentes: “Me dá um copo”, “Beija o urso”, e “Fecha a caixa”. Passar requer o desempenho correto em cinco tentativas.',
    #
    'nv4_cex_01' : 'A criança responde corretamente a questões sobre estes conceitos (Ex. Por que lava as mãos?”, “Como escova os dentes?”).',
    'nv4_cex_02' : 'Consegue descrever as funções de cinco ou mais objetos comuns com frases simples.',
    'nv4_cex_03' : 'Numa variedade de contextos, parceiros e atividades.',
    'nv4_cex_04' : 'Combina uma variedade de palavras para fazer frases nominais que podem ter até quatro palavras, incluindo artigos, possessivos, adjetivos e quantificadores (p.e., “O cavalo pequeno”, “A minha caneta vermelha”, “Este caminhão”, “Duas bolachas”, “O quadrado vermelho grande”, “Mais algumas batatas fritas”).',
    'nv4_cex_05' : 'A criança produz todas as preposições listadas ao lado para descrever arranjos de objetos, responder a perguntas e instruir os outros tanto em formatos naturais como estruturados.',
    'nv4_cex_06' : 'Autoexplicativo.',
    'nv4_cex_07' : 'Demonstra uma produção precisa de 80% dos sons durante a conversa; a inteligibilidade é considerada boa por um ouvinte estranho.',
    'nv4_cex_08' : 'Diante uma pergunta, a criança descreve uma experiência recente com pelo menos dois componentes da experiência (Que, o quê, onde, quando). Ex.: “O que fez no seu aniversário?”, “Ganhei presentes do Davi”).',
    'nv4_cex_09' : 'Pede autorização antes de começar uma atividade regulamentada: “Posso mexer?” (panela no fogo), “Posso fazer isto?” (usando uma ferramenta de adulto). Também é usado se a criança quer trocar de atividade: “Podemos ouvir música?”.',
    'nv4_cex_10' : 'Usa plurais regulares de forma consistente e espontânea e usa também duas formas irregulares (p.e., pires, lápis).',
    'nv4_cex_11' : 'Usa-os de forma regular.',
    'nv4_cex_12' : 'Usa as formas do passado de forma espontânea e regular.',
    'nv4_cex_13' : 'Aplica-os de forma consistente em frases.',
    'nv4_cex_14' : 'Usa cinco ou mais corretamente: melhor, o melhor, maior, o maior, menor, o menor, mais gordo, o mais gordo.',
    'nv4_cex_15' : 'Ex.: “Eu não estou chorando”, “Eu não bati”, “Eu não vou sentar”.',
    'nv4_cex_16' : 'Verbaliza uma frase incluindo uma forma verbal, estou/está/estão com verbo terminado em “ndo”, p.e., “O menino está andando”,',
    'nv4_cex_17' : 'Usa cinco ou mais palavras para descrever o seu estado: “Tenho fome, frio, sede, cansaço, dor”.',
    'nv4_cex_18' : 'Responde corretamente a cinco ou mais.',
    'nv4_cex_19' : 'Refere-se a um item ou a um conjunto de itens pela sua categoria. Ex.: animais, transportes, comida, roupas.',
    'nv4_cex_20' : 'Consegue nomear três ou mais características de cinco objetos comuns quando lhe pedem, “Fala sobre...”.',
    'nv4_cex_21' : 'Usa dois ou mais pronomes reflexivos: me, te, se, nos, vos, se. Ex.: “Nós nos vimos ontem”, “Eu me confundi”.',
    'nv4_cex_22' : 'Dirige-se ao telefone que toca, pega o fone e encosta no ouvido emitindo uma saudação verbal e chama a pessoa que o interlocutor pediu.',
    'nv4_cex_23' : 'Mantém conversas ao adicionar elementos, fazendo perguntas, comentando, partilhando experiências, etc. Consegue usar frases, mas mantém a conversa durante duas ou três tomadas de vez.',
    'nv4_cex_24' : 'Inicia uma conversa como parceiro com um comentário ou perguntas e mantém tópicos através de pelo menos quatro tomadas de vez durante a conversação.',
    'nv4_cex_25' : 'Em resposta a uma pergunta aberta (p.e., “Fale sobre tua visita na casa da vovó”), a criança irá descrever duas ou três atividades ou eventos usando frases.',
    'nv4_cex_26' : 'Quando é feita uma pergunta na qual a criança não sabe responder de forma adequada.',
    'nv4_cex_27' : 'Diz “O quê?” ou uma resposta semelhante quando não conseguiu ouvir ou entender um comentário, pergunta ou instrução que lhe é dirigida.',
    'nv4_cex_28' : 'Inicia e mantém conversas sobre uma variedade de tópicos.',
    'nv4_cex_29' : 'Demonstra o uso de estratégias de reparo (p.e., repete, reformula, combina a verbalização com o gesto, acrescenta ênfase) para esclarecer a comunicação quando não é entendida pelo parceiro.',
    'nv4_cex_30' : 'Pode responder a uma variedade de perguntas simples sobre si mesma e pode também responder a perguntas sobre pessoas muito familiares como membros da família, animais de estimação, o melhor amigo, etc.',
    #
    'nv4_cso_01' : 'Faz uma ou mais ofertas para o jogo, verbais ou gestuais, a um parceiro (“Vem brincar com o trem!”, “Vamos brincar de pega-pega”, ou acena para um colega).',
    'nv4_cso_02' : 'Usa vários termos de cortesia, incluindo, “Não, obrigado”, “Obrigado”, “De nada”, “Desculpe” e “Sinto muito”.',
    'nv4_cso_03' : 'Quando a criança está com medo, magoada ou frustrada, aproxima-se do adulto ou faz contato físico com ele (abraça, senta no colo ou segura a sua mão).',
    'nv4_cso_04' : 'Verbaliza os seus próprios sentimentos ao dizer “Estou zangado”, etc.',
    'nv4_cso_05' : 'Troca a vez com os adultos/pares quando envolvido numa atividade de jogo sem tomadas de vez definidas.',
    'nv4_cso_06' : 'Reconta verbalmente uma história a um colega ou irmão, incluindo pelo menos três detalhes.',
    'nv4_cso_07' : 'Verbaliza um ou mais exemplos para cada conceito (p.e., feliz, triste, zangada, assustada). Ex.: O adulto diz, “Porque está triste?” e a criança responde “Ela tirou o livro e estou triste”.',
    'nv4_cso_08' : 'Durantes as atividades de leitura ou conversação, a criança responde adequadamente quando perguntado: “Porque é que ela está chorando?” ou “Porque ele está com medo?”.',
    'nv4_cso_09' : 'Envolve-se em uma ou mais estratégias para lidar com situações. Ex.: pede uma pausa, pede ajuda, vem para dar um abraço, vai buscar um objeto de conforto.',
    #
    'nv4_cog_01' : 'Conta em voz alta de um a 20 na ordem correta.',
    'nv4_cog_02' : 'Toca ou aponta para imagens ou objetos enquanto conta em sequência, tocando ou apontando uma vez para cada número.',
    'nv4_cog_03' : 'Entrega ao adulto o número correto de itens quando o adulto pede.',
    'nv4_cog_04' : 'Entrega ao adulto o número correto de itens quando o adulto pede (“Me dá cinco bolachas” ou “Pode me dar duas almofadas”).',
    'nv4_cog_05' : 'Verbaliza dois ou mais conceitos, incluindo “um”, “alguns” ou “todos”.',
    'nv4_cog_06' : 'Verbaliza dois oi mais conceitos, incluindo “no meio”, “atrás de” ou “em frente de”.',
    'nv4_cog_07' : 'Corresponde três ou mais objetos com a palavras escrita associada de três a quatro letras.',
    'nv4_cog_08' : 'Lê e pronuncia 10 ou mais palavras de três a quatro letras para ações ou objetos comuns.',
    'nv4_cog_09' : 'Dá, aponta, mostra ou dirige-se para o seu próprio nome quando este é mostrado numa série de três nomes que inclui um nome que começa pela mesma letra que o nome da criança.',
    'nv4_cog_10' : 'Identifica o significado de três ou mais sinais e símbolos comuns. Ex.: sinal de stop, luz verde, símbolo universal do “não”.',
    'nv4_cog_11' : 'Identifica e nomeia todas as letras do alfabeto e os números de 0 – 30.',
    'nv4_cog_12' : 'Quando o adulto diz um conceito, a criança diz o conceito oposto. Ex.: “O rato é pequeno, mas o elefante é...” e a criança diz, “grande”.',
    #
    'nv4_jog_01' : 'Usa figuras e demonstra cinco ou mais ações em três ou mais contextos de jogo. Ex.: “A mamãe dirige até a loja, a irmã corre atrás do irmão e o cachorro come”.',
    'nv4_jog_02' : 'Usa três ou mais objetos neutros substitutos (neutro = sem identidade própria), Ex.: usar um bloco como telefone; um tubo como garrafa; ou uma caixa pequena como carro.',
    'nv4_jog_03' : 'Nomeia 10 ou mais ações ou adereços fazendo de conta em três ou mais atividades lúdicas de forma espontânea e em resposta a perguntas.',
    'nv4_jog_04' : 'Ex.: Despejar água na panela, mexer a comida e colocar a comida numa tigela; colocar o chapéu do bombeiro, dirigir o caminhão e apagar o fogo.',
    'nv4_jog_05' : 'Fornece três ou mais instruções relevantes direcionadas para o parceiro para realizar algum aspecto do tema em todo o jogo ao longo de dois ou mais episódios de jogo.',
    'nv4_jog_06' : 'Representa três ou mais eventos da sua vida, cada um contendo pelo menos quatro atividades incorporadas (ver item 4), interagindo com o parceiro através de guiões verbais e ações com objetos.',
    'nv4_jog_07' : 'Representa três ou mais temas da história com o parceiro usando várias ações e guiões, conforme descrito acima: Chapeuzinho vermelho, Os três porquinhos, O gato de botas.',
    'nv4_jog_08' : 'Assume um papel (p.e., “Eu sou a mamãe) e desempenha um evento da vida com um roteiro verbal, atividades e gestos, apropriadas ao papel, com três ou mais trocas com o parceiro.',
    'nv4_jog_09' : 'Segue as diretivas de jogo do parceiro, verbais ou não verbais, cinco ou mais vezes, ao imitar as ações dos parceiros ou respondendo às suas instruções.',
    #
    'nv4_mfi_01' : 'A criança pinta maioritariamente dentro das formas e escolhe cores diferentes para completar a imagem numa página de um livro para colorir.',
    'nv4_mfi_02' : 'Copia o círculo, o quadrado, o triângulo e algumas letras do alfabeto de forma reconhecível.',
    'nv4_mfi_03' : 'Começa a desenhar várias formas ou letras/números que são reconhecíveis.',
    'nv4_mfi_04' : 'Tanto copia como gera quatro a cinco formas, quatro a cinco letras e vários números que são reconhecíveis.',
    'nv4_mfi_05' : 'Autoexplicativo.',
    'nv4_mfi_06' : 'Autoexplicativo.',
    'nv4_mfi_07' : 'Mantém a cor geralmente dentro dos contornos.',
    'nv4_mfi_08' : 'Consegue acompanhar os padrões ponto-a-ponto e segue sequências com números.',
    'nv4_mfi_09' : 'Consegue ligar imagens de objetos correspondentes ou relacionados numa linha (como numa atividade escolar).',
    'nv4_mfi_10' : 'Copia cinco ou mais desenhos diferentes e faz 2-3 imagens reconhecíveis espontaneamente.',
    'nv4_mfi_11' : 'Autoexplicativo; seguindo o modelo.',
    'nv4_mfi_12' : 'Corta os cantos e os contornos de grandes formatos (7cm ou mais) com uma tesoura de criança de forma independente.',
    'nv4_mfi_13' : 'Corta com sucesso figuras com 7 cm.',
    'nv4_mfi_14' : 'Assim que o adulto modela a atividade, a criança pode sequenciar a atividade e concluí-la de forma autônoma, desde que cada etapa envolva uma competência em que a criança é totalmente competente.',
    'nv4_mfi_15' : 'Usa uma variedade de materiais de arte em atividades de expressão plástica livres para criar produtos. Também pode imitar o modelo do adulto usando cada uma dessas ferramentas.',
    'nv4_mfi_16' : 'Segura consistentemente o material de escrita com uma preensão tripla.',
    'nv4_mfi_17' : 'Reúne uma variedade de materiais de construção em projetos complexos e também pode copiar os projetos dos outros, tanto a partir de modelos 3D como de imagens e desenhos a lápis. Pode demonstrar cinco ou mais modelos diferentes.',
    'nv4_mfi_18' : 'Autoexplicativo.',
    'nv4_mfi_19' : 'Usa todas estas ferramentas de forma independente.',
    #
    'nv4_mgr_01' : 'Pode manter o jogo da apanhada durante seis ou mais tomadas de vez.',
    'nv4_mgr_02' : 'Autoexplicativo.',
    'nv4_mgr_03' : 'Autoexplicativo, para todo equipamento adequado para a idade.',
    'nv4_mgr_04' : 'A criança ajusta o corpo e dá pontapés com sucesso na bola em movimento.',
    'nv4_mgr_05' : 'Joga cinco ou mais jogos com bola.',
    'nv4_mgr_06' : 'Autoexplicativo.',
    'nv4_mgr_07' : 'Imita ambos e executa sem problemas.',    
    'nv4_mgr_08' : 'Autoexplicativo; caminha de forma relativamente calma e não muito lentamente.',
    'nv4_mgr_09' : 'Joga cinco ou mais destes jogos – conhece as regras e participa ativamente ao longo do jogo e sem ajudas ou treino.',
    #
    'nv4_ipe_01' : 'Vai ao banheiro conforme necessário (embora o adulto possa solicitar idas ao banheiro), puxa as próprias roupas para baixo e para cima; dá descarga e lava as mãos.',
    'nv4_ipe_02' : 'Vai sozinha ao banheiro (sem precisar da ajuda do adulto).',
    'nv4_ipe_03' : 'Abre a torneira, coloca as mãos embaixo da água, coloca sabão, esfrega as mãos, tira o sabão, fecha a torneira e seca as mãos com a toalha.',
    'nv4_ipe_04' : 'Durante o banho, a criança molha a esponja, aplica o sabão e esfrega o rosto com a esponja.',
    'nv4_ipe_05' : 'Quando o adulto pede para criança pentear o cabelo, a criança pega no utensílio passando-o no cabelo. Pode haver exceções apropriadas mediante a idade para as dificuldades com cabelos longos ou encaracolados.',
    'nv4_ipe_06' : 'Esfrega o corpo com a esponja, aplica sabão no corpo, e esfrega o próprio couro cabeludo quando o shampoo é aplicado. Seca-se razoavelmente bem; pode precisar de “estímulo”.',
    'nv4_ipe_07' : 'Estando a pasta e a escova no lugar próprio, a criança consegue realizar todas as etapas de forma autônoma.',
    'nv4_ipe_08' : 'Aperta os próprios botões, fechos e molas quando estes estão presentes na sua roupa.',
    'nv4_ipe_09' : 'Quando o adulto diz, “Assoa o nariz”, a criança pega num lenço e assoa o nariz com o lenço. Quando a criança espirra, cobre a boca com a mão ou o braço.',
    'nv4_ipe_10' : 'Ao aproximar da calçada ou rua com o parceiro, a criança para autonomamente, espera, olha e aguarda que o parceiro indique que pode atravessar.',
    'nv4_ipe_11' : 'Anda sem dar as mãos e fica perto do adulto, monitorando a localização do adulto e mantendo uma proximidade por iniciativa própria.',
    'nv4_ipe_12' : 'Consegue colocar pratos, copos, guardanapos e talheres nos lugares corretos e de forma autônoma e relativamente ordenada. O adulto pode marcar o local que os itens devem ser colocados e disponibilizar os materiais em cima da mesa.',
    'nv4_ipe_13' : 'Passa geleia ou etc, no pão, sem cortá-lo.',
    'nv4_ipe_14' : 'Limpa o que deixou cair, por iniciativa própria e faz o trabalho completo.',
    'nv4_ipe_15' : 'Coloca água no copo de uma jarra pequena.',
    'nv4_ipe_16' : 'Após a refeição, a criança limpa rotineiramente o seu lugar e coloca os utensílios de comer no lugar correto de forma autônoma.',
    'nv4_ipe_17' : 'Tira dois itens diferentes, passa-os do recipiente para o prato e coloca-os na mesa. Ex.: Prepara vegetais cortados e molho; queijo e biscoitos; passa requeijão na bolacha; cereais com leite.',
    'nv4_ipe_18' : 'Participa em vários passos da atividade de culinária com várias etapas como fazer biscoito, panquecas, ovo mexido.',

}
