description_dict = {
    'nv1_cre_01' : 'Demonstra consciência do som virando os olhos e a cabeça.',
    'nv1_cre_02' : 'Demonstra consciência do som tornando-se mais ativo, virando os olhos e a cabeça para a pessoa.',
    'nv1_cre_03' : 'Demonstra consciência da voz ao virar os olhos e cabeça para a pessoa.',
    'nv1_cre_04' : 'Segue quando adulto aponta para imagem, com o olhar e/ou gesto (p.e. tocar ou apontar a imagem).',
    'nv1_cre_05' : 'Responde ao ponto proximal olhando e colocando o objeto na localização indicada pelo adulto.',
    'nv1_cre_06' : 'Vira os olhos e a cabeça na direção do objeto. Interlocutor apresenta',
    'nv1_cre_07' : 'Vira os olhos e a cabeça em direção ao parceiro.',
    'nv1_cre_08' : 'Vira a cabeça para o objeto ou localização. Objeto próximo a ela; ela vai até ele.',
    'nv1_cre_09' : 'Aproxima-se e pega o objeto.',
    'nv1_cre_10' : 'Assiste e responde a uma ou mais tomadas de vez. Os jogos sociais incluem o "Cadê?", "Formiguinha" e Cócegas.',
    'nv1_cre_11' : 'O mesmo que no item anterior. Presta atenção e responde durante canções a um ou mais versos.',
    'nv1_cre_12' : 'Interrompe uma atividade contínua quando dito "Não", "Para", ou demonstra consciência, fazendo uma pausa temporária, virando os olhos e a cabeça para o adulto, ou mostrando angústia (p.e. chorando).',
    'nv1_cre_13' : 'Responde ao gesto e à fala do adulto, colocando ou tentando colocar o objeto na mão do adulto.',
    'nv1_cre_14' : 'Realiza a ação com pistas verbais/gestuais. Tem de executar pelo menos cinco ações na primeira oportunidade. Os exemplos incluem o adulto repetir a instrução, usar verbos para destacar a ação (p.e., bater na cadeira para sentar; segurar o balde para guardar), ou ajudar a criança parcialmente durante a ação.',
    'nv1_cre_15' : 'Executa a ação sem os gestos ou orientação física do adulto. O adulto pode repetir as instruções uma segunda vez, sem a pista gestual.',
    #
    'nv1_cex_01' : 'Tenta alcançar o objeto desejado que está nas mãos do adulto para indicar o pedido. O gesto não precisa ser acompanhado pelo contato visual ou vocalizações/palavras. Não inclui o aproximar para agarrar.',
    'nv1_cex_02' : 'Vocaliza em conjunto com o contato visual e/ou gesto (p.e. tentar alcançar) para pedir um item ou objeto desejado.',
    'nv1_cex_03' : 'Indica que precisa de ajuda oferecendo ou colocando o objeto na mão do adulto, verbalizando ou olhando para o adulto. O gesto não precisa ser acompanhado pelo contato visual ou emissões orais.',
    'nv1_cex_04' : 'Balbucia e/ou vocaliza com contato visual em pelo menos dois turnos.',
    'nv1_cex_05' : 'O gesto não precisa ser acompanhado pelo contato visual ou emissões. Considere outros gestos convencionais (balançar a cabeça, sinal de "acabou") ou emissões ("não").',
    'nv1_cex_06' : 'Toca ou aponta para o objeto a 15-30 cm com o dedo indicador (a mão não está aberta) para indicar o pedido. O objeto pode estar na mão do adulto ou ao alcance da criança.',
    'nv1_cex_07' : 'Vira a cabeça e os olhos para o adulto e faz contato visual por 1-2 segundos, com ou sem gesto (p.e. alcançar, agarrar) para solicitar o objeto. O contato visual e os gestos não precisam ser acompanhados por emissões.',
    'nv1_cex_08' : 'O adulto segura dois objetos, um em cada mão. A criança toca ou aponta para o objeto desejado com o dedo indicador (a mão não está aberta). O gesto não precisa ser acompanhado pelo contato visual ou emissões.',
    'nv1_cex_09' : 'Vira a cabeça e os olhos para o adulto e faz contato visual enquanto vocaliza para pedir o objeto desejado. A vocalização pode ser uma aproximação. P.e.: "ooh" para bola e "iih" para ir.',
    'nv1_cex_10' : 'Usa o dedo indicador (a mão não está aberta) para apontar para o objeto desejado, 90 cm ou mais de distância da criança).',
    'nv1_cex_11' : 'O adulto segura dois objetos, um em cada mão, mas fora do alcance da criança e dizendo o nome de cada objeto. A criança aponta para o objeto desejado que está longe do seu alcance com o dedo indicador (a mão não está aberta). O gesto não precisa ser acompanhado pelo contato visual ou emissões.',
    'nv1_cex_12' : 'Os exemplos incluem "ba-ba", "ma-ma". A vocalização não precisa ser acompanhada de contato visual ou gesto.',
    'nv1_cex_13' : 'As vocalizações ocorrem com ou sem modelo verbal do adulto. As vocalizações durante o jogo contam.',
    'nv1_cex_14' : 'Os exemplos incluem "ba-bu", "ma-vu" e sequências de jargão.',
    #
    'nv1_cso_01' : 'A criança não mostra evitamento, desistência ou afeto negativo.',
    'nv1_cso_02' : 'As ajudas motoras incluem: alcançar, imitar o movimento do adulto, entregar um item ou objeto ao adulto. Não precisa ser acompanhada de contato visual.',
    'nv1_cso_03' : 'Atenta ao olhar e mantém o contato visual com a outra pessoa por 2 segundos.',
    'nv1_cso_04' : 'Mostra interesse na rotina social sensorial abordando, observando ou participando ativamente e solicitando a continuação da rotina através do contato visual, gestos (p.e. alcançando, imitando o movimento do adulto) ou vocalizando.',
    'nv1_cso_05' : 'A resposta não precisa ser acompanhada de contato visual.',
    'nv1_cso_06' : 'Mostra interesse na atividade observando e imitando o adulto fazendo ações e dá continuidade ao esquema de jogo imitado.',
    'nv1_cso_07' : 'Participa duas vezes ou mais em qualquer comportamento ativo (alcançar, imitar, vocalizar) durante um jogo. O contato visual e o sorriso isolado não são suficientes. Exemplos de atividades: "Cadê o...", "Era uma vez uma formiguinha...", músicas, livros, bolinha de sabão.',
    'nv1_cso_08' : 'Demonstra consciência da saudação, virando a cabeça e olhando para o adulto por 2-3 segundos. A resposta não precisa ser acompanhada de gestos ou vocalizações.',
    'nv1_cso_09' : 'Demonstra consciência da saudação, virando a cabeça e o corpo e vocalizando "Olá/Tchau" com contato visual por 2-3 segundos.',
    'nv1_cso_10' : 'Partilha sorrisos com contato visual por 2-3 segundos durante a atividade de jogo com o adulto.',
    #
    'nv1_imi_01' : 'Imita oito ou mais ações com objetos até 5 segundos após o modelo do adulto. P.e.: bater dois objetos um contra o outro, colocar um objeto dentro de um recipiente ou rolar um objeto).',
    'nv1_imi_02' : 'Imita 10 ações motoras diferentes até 5 segundos após modelo do adulto. Imita duas ações diferentes por música em quatro a cinco rotinas diferentes.',
    'nv1_imi_03' : 'Imita seis ações diferentes. P.e.: colocar as mãos na cabeça, nas orelhas ou palmadinhas nas bochechas.',
    'nv1_imi_04' : 'Imita movimentos oro-faciais até 5 segundos após o modelo do adulto. P.e.: mostrar a língua, vibrar a língua, lábios, encher as bochechas de ar.',
    #
    'nv1_cog_01' : 'Pode ser em resposta à pista verbal ("Coloca aqui") ou física ("Mão sobre mão) do adulto nas primeiras tentativas, mas a criança precisa completar a correspondência/classificação de forma autônoma pelo menos para cinco objetos diferentes. P.e, agrupar trens e carros; lápis e papel; palitos e círculos em recipientes separados.',
    'nv1_cog_02' : 'Igual acima para pelo menos cinco imagens diferentes.',
    'nv1_cog_03' : 'Igual acima para pelo menos cinco pares de objeto/imagem diferentes.',
    'nv1_cog_04' : 'Igual acima para cinco ou mais cores.',
    #
    'nv1_jog_01' : 'A ação deve ser iniciada pela criança e não em resposta ao modelo do adulto. O comportamento adapta-se às características do objeto. P.e.: agitar o chocalho, bater com martelo, rolar ou bater a bola, ou empilhar blocos.',
    'nv1_jog_02' : 'O jogo é adequado ao desenvolvimento (p.e., não é restrito ou repetitivo), relaciona-se com o objeto/atividade e envolve ações de um passo com objetos. P.e.: inserir blocos num jogo de encaixe, colocar bolas num labirinto, colocar pinos em orifícios, desmanchar sequências de contas encaixadas.',
    'nv1_jog_03' : 'O jogo envolve a conclusão autônoma do objeto/atividade. Passa com cinco ou mais brinquedos. P.e.: inserir anéis num pino; pôr e tirar copos encaixados; empilhar blocos ou colocar pinos em orifícios.',
    'nv1_jog_04' : 'O jogo relaciona-se com o objeto/atividade e envolve ações de um passo com objetos. Passa com 8-10 brinquedos. P.e.: atirar bolas, rolar carrinhos ou bater num tambor.',
    'nv1_jog_05' : 'O jogo envolve a conclusão autônoma do objeto/atividade. Passa com 8-10 brinquedos. P.e.: colocar e tirar blocos de um recipiente; amassar e cortar papel ou juntar contas num colar e desmanchar.',
    'nv1_jog_06' : 'O jogo envolve a conclusão autônoma do objeto/atividade. Passa com 6-8 brinquedos. P.e.: abrir/fechar recipientes; colocar/tirar objetos, realizando diferentes ações com os mesmos.',
    'nv1_jog_07' : 'Ações socialmente convencionais e dirigidas para si. Podem ser em resposta ao modelo do adulto mas independentes, a utilização espontânea dos objetos é necessária em pelo menos uma ação. P.e.: colocar o telefone na orelha; escovar o cabelo com a escova; colocar o garfo/colher na boca; limpar o nariz com lenço; levar o copo aos lábios; colocar contas.',
    'nv1_jog_08' : 'Termina a atividade apropriadamente e mostra alguma tentativa de arrumar (p.e., guarda um objeto ou entrega para o adulto). Pode ser em resposta à sugestão verbal ou ao gesto do adulto para começar, mas precisa participar sem ajuda física.',
    #
    'nv1_mfi_01' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário colocar 1-2 formas autonomamente.',
    'nv1_mfi_02' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário colocar 2-3 anéis autonomamente.',
    'nv1_mfi_03' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário três ou mais peças autonomamente.',
    'nv1_mfi_04' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário colocar três ou mais pinos autonomamente.',
    'nv1_mfi_05' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas tem que apertar os botões autonomamente.',
    'nv1_mfi_06' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas tem de separar três ou mais peças ou legos autonomamente.',
    'nv1_mfi_07' : 'O adulto pode colocar o brinquedo ao alcance da criança mas sem outras facilidades.',
    'nv1_mfi_08' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário empilhar pelo menos três blocos ou copos autonomamente.',
    'nv1_mfi_09' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário segurar e fazer marcas autonomamente. As marcas não precisam ter uma forma reconhecível.',
    'nv1_mfi_10' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário segurar e bater no brinquedo autonomamente.',
    'nv1_mfi_11' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário segurar nos objetos e encher a colher/usar o balde/despejar autonomamente.',
    'nv1_mfi_12' : 'Pode ser em resposta à sugestão do adulto para começar a rotina, mas é necessário empilhar pelo menos três peças autonomamente.',
    #
    'nv1_mgr_01' : 'Não pode agarrar o adulto ou objeto (mesa, cadeira) para chutar a bola. Mantém equilíbrio, não cai, pode ser desajeitado.',
    'nv1_mgr_02' : 'Pode segurar no corrimão ou dar a mão ao adulto, colocando os dois pés em cada degrau. Não pode colocar as mãos nem os joelhos nos degraus.',
    'nv1_mgr_03' : 'Deve fazer sem ajuda.',
    'nv1_mgr_04' : 'Deve fazer sem ajuda em brinquedos de montar, cavalo de balanço ou cadeiras para criança ou adulto.',
    'nv1_mgr_05' : 'Usa reações de proteção ou de equilíbrio (estica as mãos, estende os braços, protege a cabeça).',
    'nv1_mgr_06' : 'Mostra consciência do corpo em relação aos objetos passando por cima ou caminhando em redor dos objetos.',
    'nv1_mgr_07' : 'Deve fazer com ajuda e com orientação espacial para frente.',
    'nv1_mgr_08' : 'O adulto pode começar a rotina mas, a criança mostra interesse fazendo rolar o brinquedo em direção à pessoa.',
    #
    'nv1_com_01' : 'Comportamentos autoagressivos, agressão, birras frequentes e/ou graves.',
    'nv1_com_02' : 'Senta-se calmamente/feliz durante pelo menos 60 segundos, enquanto interage com o adulto.',
    'nv1_com_03' : 'Os jogos podem incluir "Cadê/Achou", canções ou rotinas físicas (cócegas, subir e descer do colo do adulto).',
    'nv1_com_04' : 'As solicitações dos adultos são dentro do conjunto das competências atuais da criança. As birras podem ocorrer mas sem comportamento agressivo.',
    'nv1_com_05' : 'Sem agressão ou outras interações inapropriadas observadas no relatório dos pais.',
    #
    'nv1_ipe_01' : 'Senta à mesa durante a refeição (não se levanta ou anda ou sai da mesa durante a refeição). Não precisa manter-se durante toda a refeição da família.',
    'nv1_ipe_02' : 'O adulto prepara a comida mas, não é preciso nenhum outro tipo de assistência.',
    'nv1_ipe_03' : 'Segura e coloca o copo na boca sem ajuda. É possível sorver um pouco de líquido enquanto bebe.',
    'nv1_ipe_04' : 'Segura e coloca a colher na boca sem ajuda na maioria das colheradas. Pode deixar cair ocasionalmente.',
    'nv1_ipe_05' : 'Segura e coloca o garfo na boca sem ajuda na maioria das dentadas. Pode deixar cair ocasionalmente.',
    'nv1_ipe_06' : 'O relatório dos pais é suficiente.',
    'nv1_ipe_07' : 'Permite que um alimento novo fique no prato e tenta comer (toca, cheira ou coloca na boca). Não tem que comer.',
    'nv1_ipe_08' : 'O adulto pode colocar o canudo na boca da criança se ela nunca tomou antes.',
    'nv1_ipe_09' : 'Não precisa desabotoar ou abrir o zíper das roupas, mas deve conseguir tirar itens com ajuda. P.e., o adulto tira os braços e a criança a cabeça da camiseta; o adulto desabotoa a calça e a criança tira.',
    'nv1_ipe_10' : 'Não precisa abotoar ou fechar o zíper das roupas, mas deve vestir um item com ajuda. P.e.: o adulto estica a camiseta e a criança passa a cabeça; segura o sapato e a criança coloca o pé; o adulto coloca os pés da calça e a criança sobre.',
    'nv1_ipe_11' : 'Pode ser ajudado, se necessário, mas é capaz de colocar as mãos debaixo da água durante pelo menos 5 segundos. O relatório dos pais é suficiente.',
    'nv1_ipe_12' : 'Pode ser ajudado, se necessário, mas usa uma toalha para secar ambas as mãos. O relatório dos pais é suficiente.',
    'nv1_ipe_13' : 'Pode ser ajudado, se necessário, mas usa uma toalha em muitas partes do corpo (p.e. rosto, mãos, barriga, pernas). O relatório dos pais é suficiente.',
    'nv1_ipe_14' : 'Pode fazer birra, mas é capaz de terminar a rotina sem agressividade ou problemas de autoagressão ou de comportamentos graves.',
    'nv1_ipe_15' : 'P.e.: segura a escova/pente, ou toma a vez.',
    'nv1_ipe_16' : 'Coloca a escova de dentes na boca, saboreia a pasta. Não tem que escovar os dentes.',
    'nv1_ipe_17' : 'Pode ser lembrado ou receber ajuda física se necessário (p.e. adulto entrega a roupa, aponta para o cesto), mas é capaz de colocar as roupas no cesto.',
    'nv1_ipe_18' : 'Pode ser lembrado ou receber ajuda física se necessário (p.e. adulto entrega o lenço, aponta o lixo), mas é capaz de jogar os lenços no lixo.',

    ##########

    'nv2_cre_01' : 'A criança responde a instruções verbais isoladas; para cada atividade por completo, olha para o adulto e espera a instrução.',
    'nv2_cre_02' : '',
    'nv2_cre_03' : '',
    'nv2_cre_04' : '',
    'nv2_cre_05' : '',
    'nv2_cre_06' : '',
    'nv2_cre_07' : '',
    'nv2_cre_08' : '',
    'nv2_cre_09' : '',
    'nv2_cre_10' : '',
    #
    'nv2_cex_01' : '',
    'nv2_cex_02' : '',
    'nv2_cex_03' : '',
    'nv2_cex_04' : '',
    'nv2_cex_05' : '',
    'nv2_cex_06' : '',
    'nv2_cex_07' : '',
    'nv2_cex_08' : '',
    'nv2_cex_09' : '',
    'nv2_cex_10' : '',
    'nv2_cex_11' : '',
    'nv2_cex_12' : '',
    #
    'nv2_cac_01' : '',
    'nv2_cac_02' : '',
    'nv2_cac_03' : '',
    'nv2_cac_04' : '',
    'nv2_cac_05' : '',
    'nv2_cac_06' : '',
    'nv2_cac_07' : '',
    'nv2_cac_08' : '',
    #
    'nv2_cso_01' : '',
    'nv2_cso_02' : '',
    'nv2_cso_03' : '',
    'nv2_cso_04' : '',
    'nv2_cso_05' : '',
    'nv2_cso_06' : '',
    'nv2_cso_07' : '',
    'nv2_cso_08' : '',
    'nv2_cso_09' : '',
    'nv2_cso_10' : '',
    'nv2_cso_11' : '',
    'nv2_cso_12' : '',
    'nv2_cso_13' : '',
    'nv2_cso_14' : '',
    'nv2_cso_15' : '',
    'nv2_cso_16' : '',
    'nv2_cso_17' : '',
    'nv2_cso_18' : '',
    'nv2_cso_19' : '',
    'nv2_cso_20' : '',

    #

    'nv2_imi_01' : '',
    'nv2_imi_02' : '',
    'nv2_imi_03' : '',
    'nv2_imi_04' : '',
    'nv2_imi_05' : '',
    'nv2_imi_06' : '',
    'nv2_imi_07' : '',
    'nv2_imi_08' : '',
    'nv2_imi_09' : '',
    #
    'nv2_cog_01' : '',
    'nv2_cog_02' : '',
    'nv2_cog_03' : '',
    'nv2_cog_04' : '',
    'nv2_cog_05' : '',
    'nv2_cog_06' : '',
    'nv2_cog_07' : '',
    'nv2_cog_08' : '',
    #
    'nv2_jog_01' : '',
    'nv2_jog_02' : '',
    'nv2_jog_03' : '',
    'nv2_jog_04' : '',
    'nv2_jog_05' : '',
    'nv2_jog_06' : '',
    'nv2_jog_07' : '',
    'nv2_jog_08' : '',
    #
    'nv2_mfi_01' : '',
    'nv2_mfi_02' : '',
    'nv2_mfi_03' : '',
    'nv2_mfi_04' : '',
    'nv2_mfi_05' : '',
    'nv2_mfi_06' : '',
    'nv2_mfi_07' : '',
    'nv2_mfi_08' : '',
    'nv2_mfi_09' : '',
    'nv2_mfi_10' : '',
    'nv2_mfi_11' : '',
    'nv2_mfi_12' : '',
    #
    'nv2_mgr_01' : '',
    'nv2_mgr_02' : '',
    'nv2_mgr_03' : '',
    'nv2_mgr_04' : '',
    'nv2_mgr_05' : '',
    'nv2_mgr_06' : '',
    'nv2_mgr_07' : '',
    #
    'nv2_com_01' : '',
    'nv2_com_02' : '',
    'nv2_com_03' : '',
    'nv2_com_04' : '',
    'nv2_com_05' : '',
    #
    'nv2_ipe_01' : '',
    'nv2_ipe_02' : '',
    'nv2_ipe_03' : '',
    'nv2_ipe_04' : '',
    'nv2_ipe_05' : '',
    'nv2_ipe_06' : '',
    'nv2_ipe_07' : '',
    'nv2_ipe_08' : '',
    'nv2_ipe_09' : '',
    'nv2_ipe_10' : '',
    'nv2_ipe_11' : '',
    'nv2_ipe_12' : '',
    'nv2_ipe_13' : '',
    'nv2_ipe_14' : '',
    'nv2_ipe_15' : '',
    'nv2_ipe_16' : '',
    'nv2_ipe_17' : '',

    ##########

    'nv3_cre_01' : '',
    'nv3_cre_02' : '',
    'nv3_cre_03' : '',
    'nv3_cre_04' : '',
    'nv3_cre_05' : '',
    'nv3_cre_06' : '',
    'nv3_cre_07' : '',
    'nv3_cre_08' : '',
    'nv3_cre_09' : '',
    'nv3_cre_10' : '',
    'nv3_cre_11' : '',
    'nv3_cre_12' : '',
    'nv3_cre_13' : '',
    'nv3_cre_14' : '',
    #
    'nv3_cex_01' : '',
    'nv3_cex_02' : '',
    'nv3_cex_03' : '',
    'nv3_cex_04' : '',
    'nv3_cex_05' : '',
    'nv3_cex_06' : '',
    'nv3_cex_07' : '',
    'nv3_cex_08' : '',
    'nv3_cex_09' : '',
    'nv3_cex_10' : '',
    'nv3_cex_11' : '',
    'nv3_cex_12' : '',
    'nv3_cex_13' : '',
    'nv3_cex_14' : '',
    'nv3_cex_15' : '',
    'nv3_cex_16' : '',
    'nv3_cex_17' : '',
    'nv3_cex_18' : '',
    #
    'nv3_cso_01' : '',
    'nv3_cso_02' : '',
    'nv3_cso_03' : '',
    'nv3_cso_04' : '',
    'nv3_cso_05' : '',
    'nv3_cso_06' : '',
    'nv3_cso_07' : '',
    'nv3_cso_08' : '',
    'nv3_cso_09' : '',
    'nv3_cso_10' : '',
    'nv3_cso_11' : '',
    'nv3_cso_12' : '',
    'nv3_cso_13' : '',
    'nv3_cso_14' : '',
    'nv3_cso_15' : '',
    # 
    'nv3_cog_01' : '',
    'nv3_cog_02' : '',
    'nv3_cog_03' : '',
    'nv3_cog_04' : '',
    'nv3_cog_05' : '',
    'nv3_cog_06' : '',
    'nv3_cog_07' : '',
    'nv3_cog_08' : '',
    'nv3_cog_09' : '',
    'nv3_cog_10' : '',
    #
    'nv3_jog_01' : '',
    'nv3_jog_02' : '',
    'nv3_jog_03' : '',
    'nv3_jog_04' : '',
    'nv3_jog_05' : '',
    'nv3_jog_06' : '',
    #
    'nv3_mfi_01' : '',
    'nv3_mfi_02' : '',
    'nv3_mfi_03' : '',
    'nv3_mfi_04' : '',
    'nv3_mfi_05' : '',
    'nv3_mfi_06' : '',
    'nv3_mfi_07' : '',
    'nv3_mfi_08' : '',
    'nv3_mfi_09' : '',
    'nv3_mfi_10' : '',
    'nv3_mfi_11' : '',
    #
    'nv3_mgr_01' : '',
    'nv3_mgr_02' : '',
    'nv3_mgr_03' : '',
    'nv3_mgr_04' : '',
    'nv3_mgr_05' : '',
    'nv3_mgr_06' : '',
    'nv3_mgr_07' : '',
    'nv3_mgr_08' : '',
    #
    'nv3_ipe_01' : '',
    'nv3_ipe_02' : '',
    'nv3_ipe_03' : '',
    'nv3_ipe_04' : '',
    'nv3_ipe_05' : '',
    'nv3_ipe_06' : '',
    'nv3_ipe_07' : '',
    'nv3_ipe_08' : '',
    'nv3_ipe_09' : '',
    'nv3_ipe_10' : '',
    'nv3_ipe_11' : '',
    'nv3_ipe_12' : '',
    'nv3_ipe_13' : '',
    'nv3_ipe_14' : '',
    'nv3_ipe_15' : '',
    'nv3_ipe_16' : '',
    'nv3_ipe_17' : '',
    'nv3_ipe_18' : '',
    'nv3_ipe_19' : '',

    ##########

    'nv4_cre_01' : '',
    'nv4_cre_02' : '',
    'nv4_cre_03' : '',
    'nv4_cre_04' : '',
    'nv4_cre_05' : '',
    'nv4_cre_06' : '',
    'nv4_cre_07' : '',
    'nv4_cre_08' : '',
    'nv4_cre_09' : '',
    'nv4_cre_10' : '',
    'nv4_cre_11' : '',
    'nv4_cre_12' : '',
    'nv4_cre_13' : '',
    'nv4_cre_14' : '',
    'nv4_cre_15' : '',
    'nv4_cre_16' : '',
    'nv4_cre_17' : '',
    'nv4_cre_18' : '',
    'nv4_cre_19' : '',
    #
    'nv4_cex_01' : '',
    'nv4_cex_02' : '',
    'nv4_cex_03' : '',
    'nv4_cex_04' : '',
    'nv4_cex_05' : '',
    'nv4_cex_06' : '',
    'nv4_cex_07' : '',
    'nv4_cex_08' : '',
    'nv4_cex_09' : '',
    'nv4_cex_10' : '',
    'nv4_cex_11' : '',
    'nv4_cex_12' : '',
    'nv4_cex_13' : '',
    'nv4_cex_14' : '',
    'nv4_cex_15' : '',
    'nv4_cex_16' : '',
    'nv4_cex_17' : '',
    'nv4_cex_18' : '',
    'nv4_cex_19' : '',
    'nv4_cex_20' : '',
    'nv4_cex_21' : '',
    'nv4_cex_22' : '',
    'nv4_cex_23' : '',
    'nv4_cex_24' : '',
    'nv4_cex_25' : '',
    'nv4_cex_26' : '',
    'nv4_cex_27' : '',
    'nv4_cex_28' : '',
    'nv4_cex_29' : '',
    'nv4_cex_30' : '',
    #
    'nv4_cso_01' : '',
    'nv4_cso_02' : '',
    'nv4_cso_03' : '',
    'nv4_cso_04' : '',
    'nv4_cso_05' : '',
    'nv4_cso_06' : '',
    'nv4_cso_07' : '',
    'nv4_cso_08' : '',
    'nv4_cso_09' : '',
    #
    'nv4_cog_01' : '',
    'nv4_cog_02' : '',
    'nv4_cog_03' : '',
    'nv4_cog_04' : '',
    'nv4_cog_05' : '',
    'nv4_cog_06' : '',
    'nv4_cog_07' : '',
    'nv4_cog_08' : '',
    'nv4_cog_09' : '',
    'nv4_cog_10' : '',
    'nv4_cog_11' : '',
    'nv4_cog_12' : '',
    #
    'nv4_jog_01' : '',
    'nv4_jog_02' : '',
    'nv4_jog_03' : '',
    'nv4_jog_04' : '',
    'nv4_jog_05' : '',
    'nv4_jog_06' : '',
    'nv4_jog_07' : '',
    'nv4_jog_08' : '',
    'nv4_jog_09' : '',
    #
    'nv4_mfi_01' : '',
    'nv4_mfi_02' : '',
    'nv4_mfi_03' : '',
    'nv4_mfi_04' : '',
    'nv4_mfi_05' : '',
    'nv4_mfi_06' : '',
    'nv4_mfi_07' : '',
    'nv4_mfi_08' : '',
    'nv4_mfi_09' : '',
    'nv4_mfi_10' : '',
    'nv4_mfi_11' : '',
    'nv4_mfi_12' : '',
    'nv4_mfi_13' : '',
    'nv4_mfi_14' : '',
    'nv4_mfi_15' : '',
    'nv4_mfi_16' : '',
    'nv4_mfi_17' : '',
    'nv4_mfi_18' : '',
    'nv4_mfi_19' : '',
    #
    'nv4_mgr_01' : '',
    'nv4_mgr_02' : '',
    'nv4_mgr_03' : '',
    'nv4_mgr_04' : '',
    'nv4_mgr_05' : '',
    'nv4_mgr_06' : '',
    'nv4_mgr_07' : '',    
    'nv4_mgr_08' : '',
    'nv4_mgr_09' : '',
    #
    'nv4_ipe_01' : '',
    'nv4_ipe_02' : '',
    'nv4_ipe_03' : '',
    'nv4_ipe_04' : '',
    'nv4_ipe_05' : '',
    'nv4_ipe_06' : '',
    'nv4_ipe_07' : '',
    'nv4_ipe_08' : '',
    'nv4_ipe_09' : '',
    'nv4_ipe_10' : '',
    'nv4_ipe_11' : '',
    'nv4_ipe_12' : '',
    'nv4_ipe_13' : '',
    'nv4_ipe_14' : '',
    'nv4_ipe_15' : '',
    'nv4_ipe_16' : '',
    'nv4_ipe_17' : '',
    'nv4_ipe_18' : '',

}